<a href="https://colab.research.google.com/github/coderzaman/Numpy-For-AI-ML/blob/main/Numpy_For__AI_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to NumPy**


NumPy stands for **Num**erical **Py**thon. It's a fundamental library for scientific computing in Python.

At its core, NumPy provides a powerful object called an `ndarray`, which stands for **n-dimensional array**. This object is the key to NumPy's speed and power.

-----

## **Why is NumPy Faster than a Python List?**

While a NumPy `ndarray` might seem similar to a Python `list`, it has crucial architectural differences that make it significantly faster for numerical operations. The two main reasons are **data type homogeneity** and **contiguous memory layout**.

### **1. Homogeneous Data Types**

A NumPy array is **homogeneous**, meaning all elements inside the array must be of the **same data type** (e.g., all 32-bit integers or all 64-bit floats).

  * **NumPy `ndarray`**: Since every element is the same type, NumPy knows exactly how much memory each element takes up and doesn't need to perform type-checking when iterating or performing operations.
  * **Python `list`**: A list is **heterogeneous**. It can contain different data types (`int`, `string`, `object`, etc.). When you perform an operation on a list, Python must check the data type of each element before it can proceed, which adds significant overhead and slows down the process.

### **2. Contiguous Memory Layout**

This is the most important reason for NumPy's speed advantage.

  * **NumPy `ndarray`**: Array data is stored in a single, **contiguous block of memory**. This means if the first element is at memory address 1000, the next element (of the same integer type) will be right next to it at 1004, the next at 1008, and so on. Computers are highly optimized to work with contiguous memory blocks. This is often called being "cache-friendly."

  * **Python `list`**: A list doesn't store the actual data items contiguously. Instead, it stores **pointers** to objects that are scattered across different locations in memory. To access the next item, the program has to follow the pointer to find it, an extra step that slows things down.

-----

## **The Power of Vectorization & SIMD(Single Instruction Multiple Data)**

These two features—homogeneous types and contiguous memory—unlock a powerful programming paradigm called **vectorization**.

**Vectorization** is the process of executing operations on entire arrays at once, instead of iterating through elements one by one with a `for` loop.

For example, to multiply every element in a list by 5, you would write a loop:

```python
my_list = [1, 2, 3, 4, 5]
for i in range(len(my_list)):
    my_list[i] = my_list[i] * 5
```

With NumPy, you can perform this operation on the whole array in a single line:

```python
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])
my_array = my_array * 5 # This is vectorization!
```

This is possible because NumPy can pass the entire block of contiguous data to highly optimized, pre-compiled C code. This code, in turn, can leverage modern CPU features like **SIMD (Single Instruction, Multiple Data)**. SIMD allows a single CPU instruction (e.g., "multiply by 5") to be performed on multiple data elements simultaneously, leading to massive performance gains.

-----

## **What Else is NumPy Used For? 🧑‍🔬**

Because of its speed and efficiency, NumPy is the foundation of the scientific Python ecosystem. It provides a vast library of high-level mathematical functions that operate on `ndarray`s, including:

  * **Linear Algebra**: Matrix multiplication, determinants, solving linear equations, and more.
  * **Statistics**: Calculating mean, median, standard deviation, etc.
  * **Fourier Transforms** and routines for shape manipulation.
  * It serves as the underlying data structure for other major libraries, most notably **Pandas**, **SciPy**, and **Scikit-learn**.

## **NumPy পরিচিতি**


NumPy-এর পূর্ণরূপ হলো **Num**erical **Py**thon। এটি পাইথনে সায়েন্টিফিক কম্পিউটিং-এর জন্য একটি মৌলিক লাইব্রেরি।

NumPy-এর কেন্দ্রে রয়েছে `ndarray` নামক একটি শক্তিশালী অবজেক্ট, যার অর্থ **n-dimensional array** (এন-ডাইমেনশনাল অ্যারে)। এই অবজেক্টটিই NumPy-এর গতি এবং ক্ষমতার মূল চাবিকাঠি।

-----

## **NumPy কেন Python List-এর চেয়ে দ্রুত?**

যদিও একটি NumPy `ndarray`-কে পাইথনের `list`-এর মতোই মনে হতে পারে, তবে এর কিছু গুরুত্বপূর্ণ আর্কিটেকচারাল পার্থক্য রয়েছে যা এটিকে নিউমেরিক্যাল অপারেশনের জন্য অনেক বেশি দ্রুত করে তোলে। এর দুটি প্রধান কারণ হলো **সমজাতীয় ডেটা টাইপ** এবং **ধারাবাহিক মেমরি লেআউট**।

### **১. সমজাতীয় ডেটা টাইপ (Homogeneous Data Types)**

একটি NumPy অ্যারে **সমজাতীয় (homogeneous)** হয়, অর্থাৎ অ্যারের ভিতরের সমস্ত উপাদান অবশ্যই **একই ডেটা টাইপের** হতে হবে (যেমন, সব 32-bit integer অথবা সব 64-bit float)।

  * **NumPy `ndarray`**: যেহেতু প্রতিটি উপাদান একই ধরনের, তাই NumPy ঠিকভাবে জানে প্রতিটি উপাদানের জন্য কতটা মেমরি প্রয়োজন। এর ফলে কোনো অপারেশন চালানোর সময় ডেটা টাইপ চেক করার প্রয়োজন হয় না।
  * **Python `list`**: একটি লিস্ট **বিষমজাতীয় (heterogeneous)** হতে পারে। এতে বিভিন্ন ডেটা টাইপের উপাদান (`int`, `string`, `object` ইত্যাদি) থাকতে পারে। যখন একটি লিস্টের উপর কোনো অপারেশন করা হয়, তখন পাইথনকে প্রতিটি উপাদানের ডেটা টাইপ পরীক্ষা করতে হয়, যা অতিরিক্ত সময় নেয় এবং প্রক্রিয়াটিকে ধীর করে দেয়।

### **২. ধারাবাহিক মেমরি লেআউট (Contiguous Memory Layout)**

NumPy-এর গতির পেছনে এটিই সবচেয়ে গুরুত্বপূর্ণ কারণ।

  * **NumPy `ndarray`**: অ্যারের ডেটা একটিমাত্র, **ধারাবাহিক মেমরি ব্লকে (contiguous block of memory)** সংরক্ষিত থাকে। এর মানে হলো, যদি প্রথম উপাদানটি মেমরি অ্যাড্রেস 1000-এ থাকে, তবে পরবর্তী (একই টাইপের) উপাদানটি ঠিক তার পাশেই 1004-এ থাকবে, তার পরেরটি 1008-এ, এবং এভাবেই চলতে থাকবে। কম্পিউটার এই ধরনের ধারাবাহিক মেমরি ব্লকের সাথে কাজ করতে অত্যন্ত অপ্টিমাইজড। একে প্রায়শই "ক্যাশ-ফ্রেন্ডলি" (cache-friendly) বলা হয়।

  * **Python `list`**: একটি লিস্ট তার আসল ডেটা আইটেমগুলো ধারাবাহিকভাবে সংরক্ষণ করে না। পরিবর্তে, এটি মেমরির বিভিন্ন স্থানে ছড়িয়ে ছিটিয়ে থাকা অবজেক্টগুলোর **পয়েন্টার (pointers)** সংরক্ষণ করে। পরবর্তী আইটেমটি অ্যাক্সেস করার জন্য, প্রোগ্রামকে সেই পয়েন্টার অনুসরণ করে তাকে খুঁজে বের করতে হয়, যা একটি অতিরিক্ত ধাপ এবং প্রক্রিয়াটিকে ধীর করে দেয়।

-----

## **ভেক্টরাইজেশন এবং SIMD(Single Instruction Multiple Data)-এর শক্তি**

এই দুটি বৈশিষ্ট্য—সমজাতীয় টাইপ এবং ধারাবাহিক মেমরি—একটি শক্তিশালী প্রোগ্রামিং কৌশলকে সম্ভব করে তোলে, যার নাম **ভেক্টরাইজেশন (vectorization)**।

**ভেক্টরাইজেশন** হলো `for` লুপ ব্যবহার করে এক এক করে উপাদানের উপর কাজ না করে, একবারে পুরো অ্যারের উপর অপারেশন চালানো।

উদাহরণস্বরূপ, একটি লিস্টের প্রতিটি উপাদানকে 5 দিয়ে গুণ করতে, আপনাকে একটি লুপ লিখতে হবে:

```python
my_list = [1, 2, 3, 4, 5]
for i in range(len(my_list)):
    my_list[i] = my_list[i] * 5
```

কিন্তু NumPy ব্যবহার করে, আপনি এই কাজটি একটিমাত্র লাইনে পুরো অ্যারের উপর করতে পারেন:

```python
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])
my_array = my_array * 5 # এটাই ভেক্টরাইজেশন!
```

এটি সম্ভব কারণ NumPy পুরো ধারাবাহিক ডেটা ব্লকটিকে অত্যন্ত অপ্টিমাইজড এবং প্রি-কম্পাইলড C কোডের কাছে পাঠাতে পারে। এই C কোডটি আধুনিক CPU-এর **SIMD (Single Instruction, Multiple Data)**-এর মতো ফিচার ব্যবহার করতে পারে। SIMD একটিমাত্র CPU নির্দেশকে (যেমন, "5 দ্বারা গুণ করো") একই সময়ে একাধিক ডেটা উপাদানের উপর প্রয়োগ করতে দেয়, যার ফলে গতি বৃদ্ধি পায়।

-----

## **NumPy আর কী কী কাজে ব্যবহৃত হয়? 🧑‍🔬**

এর গতি এবং কার্যকারিতার কারণে, NumPy সায়েন্টিফিক পাইথন ইকোসিস্টেমের ভিত্তি। এটি `ndarray`-এর উপর কাজ করার জন্য উচ্চ-স্তরের গাণিতিক ফাংশনের একটি বিশাল লাইব্রেরি সরবরাহ করে, যার মধ্যে রয়েছে:

  * **রৈখিক বীজগণিত (Linear Algebra)**: ম্যাট্রিক্স গুণ, ডিটারমিন্যান্ট, রৈখিক সমীকরণ সমাধান এবং আরও অনেক কিছু।
  * **পরিসংখ্যান (Statistics)**: গড় (mean), মধ্যক (median), স্ট্যান্ডার্ড ডেভিয়েশন (standard deviation) ইত্যাদি গণনা করা।
  * **ফুরিয়ার ট্রান্সফর্ম** এবং শেপ ম্যানিপুলেশনের জন্য বিভিন্ন রুটিন।
  * এটি অন্যান্য প্রধান লাইব্রেরি যেমন **Pandas**, **SciPy**, এবং **Scikit-learn**-এর মূল ডেটা স্ট্রাকচার হিসাবে কাজ করে।

# **The NumPy `ndarray` and its Attributes**

As we've learned, the core of NumPy is the **`ndarray`** (N-dimensional array). It's a collection of one or more items of the **same data type**.

Let's first understand the problem it solves by looking at a standard Python list.

-----

## **The Problem with Python Lists**

If you try to perform a mathematical operation like multiplication on a list, it doesn't behave as you might expect for numerical tasks.

```python
# A standard Python list
arr_list = [1, 2, 3]

# Multiplying the list by 5
print(arr_list * 5)
```

**Output:** `[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]`

Instead of multiplying each element by 5, Python **duplicates the list** 5 times. To get the desired result, you need to use a loop or list comprehension, which is slower for large datasets.

```python
# Using a loop to multiply each item
multiplied_list = [item * 5 for item in arr_list]
print(multiplied_list)
```

**Output:** `[5, 10, 15]`

-----

## **NumPy Arrays: The Solution ✨**

NumPy arrays allow you to perform these operations directly on the entire array. This is called **vectorization**, and it uses low-level features like **SIMD** to execute the operation on all elements at once, making it incredibly fast.

### **Creating a NumPy Array**

First, we need to import the NumPy package. The standard convention is to import it as `np`.

```python
import numpy as np

# Creating a NumPy array from a list
arr1 = np.array([1, 2, 3])

print(arr1 * 5)
print(type(arr1))
```

**Output:**

```
[ 5 10 15]
<class 'numpy.ndarray'>
```

-----

## **Dimensions in NumPy Arrays**

NumPy arrays can have any number of dimensions.

### **1D Array (Vector)**

A 1D array is the simplest form, like a single list.

```python
arr1 = np.array([1, 2, 3])
```

### **2D Array (Matrix)**

A 2D array is like a table with rows and columns. It's essentially an array of arrays.

```python
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
```

### **3D Array (Tensor)**

A 3D array can be visualized as a **collection of 2D arrays (matrices)** stacked on top of each other. This is very common in areas like image processing, where an image can be represented as three 2D arrays: one for the Red channel, one for Green, and one for Blue.

You can think of it as having **depth (or layers), rows, and columns**.

```python
arr3 = np.array([
    # First Layer (or Matrix)
    [
      [1, 2, 3],
      [4, 5, 6]
    ],
    # Second Layer (or Matrix)
    [
      [7, 8, 9],
      [10, 11, 12]
    ]
])
```

-----

## **Key Array Attributes**

You can inspect the properties of an `ndarray` using its attributes.

### **`.ndim`**

This attribute tells you the **number of dimensions** (or axes) of the array.

```python
print(f"arr1 dimensions: {arr1.ndim}") # Output: 1
print(f"arr2 dimensions: {arr2.ndim}") # Output: 2
print(f"arr3 dimensions: {arr3.ndim}") # Output: 3
```

### **`.shape`**

This attribute returns a **tuple** representing the size of the array in each dimension. It's one of the most important attributes.

```python
print(f"arr1 shape: {arr1.shape}")
print(f"arr2 shape: {arr2.shape}")
print(f"arr3 shape: {arr3.shape}")
```

**Output:**

```
arr1 shape: (3,)
arr2 shape: (2, 3)
arr3 shape: (2, 2, 3)
```

**How to read the shape tuple:**

  * `(3,)`: This is a **1D array** with **3 elements** along its single axis.
  * `(2, 3)`: This is a **2D array** with **2 rows** and **3 columns**.
  * `(2, 2, 3)`: This is a **3D array**. You can read it from left to right: It has **2 layers/matrices**. Each matrix has **2 rows** and **3 columns**.

### **`.size`**

This attribute gives you the **total number of elements** in the array. It's simply the product of the numbers in the shape tuple.

```python
print(f"arr1 size: {arr1.size}") # Output: 3
print(f"arr2 size: {arr2.size}") # Output: 2 * 3 = 6
print(f"arr3 size: {arr3.size}") # Output: 2 * 2 * 3 = 12
```

-----

### **`.dtype`**

The **`.dtype`** (data type) attribute is crucial. It tells you exactly what kind of data is stored inside the NumPy array. Since every element in a NumPy array must be of the **same type**, this attribute defines the type for the entire array.

This uniformity is a cornerstone of NumPy's efficiency. Knowing the exact data type allows NumPy to store the data in a compact, predictable way and use optimized, low-level functions for computation.

-----

### **How NumPy Determines `dtype`**

When you create a NumPy array without specifying a type, NumPy **infers** the most suitable `dtype` from the input data.

  * If you provide only integers, it will choose an integer type (like `int64`).
  * If you include even one floating-point number, it will promote the entire array to a float type (like `float64`) to avoid losing information.

Let's look at the arrays we created earlier, which all contained only integers:

```python
import numpy as np

# Let's redefine our arrays for clarity
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(f"arr1 dtype: {arr1.dtype}")
print(f"arr2 dtype: {arr2.dtype}")
print(f"arr3 dtype: {arr3.dtype}")
```

**Expected Output:**

```
arr1 dtype: int64
arr2 dtype: int64
arr3 dtype: int64
```

*(Note: The output might be `int32` on some systems, but `int64` is common. It refers to a 64-bit integer.)*

-----

### **Specifying `dtype` Manually ✍️**

You can also explicitly tell NumPy what data type to use during creation. This is useful for controlling memory usage or ensuring precision.

```python
# Create an array of 64-bit floating-point numbers
float_arr = np.array([1, 2, 3], dtype=np.float64)

print(f"Original array: {arr1}, dtype: {arr1.dtype}")
print(f"New float array: {float_arr}, dtype: {float_arr.dtype}")
```

**Output:**

```
Original array: [1 2 3], dtype: int64
New float array: [1. 2. 3.], dtype: float64
```

Notice how NumPy added a decimal point to the numbers in `float_arr` to show they are now floats.

In [ ]:
arr = [1,2,3]
print(arr*5) # it not multipy 5 on it. It duplicate this array to 5 times
# for multiplying 5 with each item we need loop which slower the operaton
arr = [i*5 for i in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


But when we use numpy array which SIMD to allow to one single operation multipy all item with value

In [ ]:
import numpy as np
arr = np.array([1,2,3])
print(arr*5)

[ 5 10 15]


## **NumPy `ndarray` এবং এর অ্যাট্রিবিউটসমূহ**

আমরা আগেই জেনেছি যে NumPy-এর মূল ভিত্তি হলো **`ndarray`** (N-dimensional array)। এটি **একই ডেটা টাইপের** এক বা একাধিক আইটেমের একটি কালেকশন।

প্রথমে চলুন দেখি, এটি কোন সমস্যার সমাধান করে এবং সাধারণ পাইথন লিস্টের সাথে এর পার্থক্য কোথায়।

-----

## **পাইথন লিস্টের সমস্যা**

আপনি যদি একটি সাধারণ পাইথন লিস্টের উপর গুণ করার মতো গাণিতিক অপারেশন করতে চান, তবে এটি নিউমেরিক্যাল কাজের জন্য প্রত্যাশিত আচরণ করে না।

```python
# একটি সাধারণ পাইথন লিস্ট
arr_list = [1, 2, 3]

# লিস্টকে 5 দিয়ে গুণ করা হলো
print(arr_list * 5)
```

**আউটপুট:** `[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]`

এখানে প্রতিটি উপাদানকে 5 দিয়ে গুণ না করে, পাইথন লিস্টটিকে 5 বার **ডুপ্লিকেট** বা পুনরাবৃত্তি করেছে। কাঙ্ক্ষিত ফলাফল পেতে, আপনাকে একটি লুপ বা লিস্ট কম্প্রিহেনশন ব্যবহার করতে হবে, যা বড় ডেটাসেটের জন্য ধীরগতির।

```python
# প্রতিটি আইটেমকে গুণ করার জন্য লুপ ব্যবহার
multiplied_list = [item * 5 for item in arr_list]
print(multiplied_list)
```

**আউটপুট:** `[5, 10, 15]`

-----

## **NumPy অ্যারে: সমাধান ✨**

NumPy অ্যারে আপনাকে এই ধরনের অপারেশন সরাসরি পুরো অ্যারের উপর করতে দেয়। একে **ভেক্টরাইজেশন (vectorization)** বলা হয় এবং এটি **SIMD**-এর মতো নিম্ন-স্তরের ফিচার ব্যবহার করে সব উপাদানের উপর একই সাথে অপারেশন চালায়, যা এটিকে অবিশ্বাস্যভাবে দ্রুত করে তোলে।

### **NumPy অ্যারে তৈরি করা**

প্রথমে, আমাদের NumPy প্যাকেজটি ইম্পোর্ট করতে হবে। সাধারণত এটিকে `np` হিসেবে ইম্পোর্ট করা হয়।

```python
import numpy as np

# একটি লিস্ট থেকে NumPy অ্যারে তৈরি করা
arr1 = np.array([1, 2, 3])

print(arr1 * 5)
print(type(arr1))
```

**আউটপুট:**

```
[ 5 10 15]
<class 'numpy.ndarray'>
```

-----

## **NumPy অ্যারেতে ডাইমেনশন (Dimension)**

NumPy অ্যারে যেকোনো সংখ্যক ডাইমেনশনের হতে পারে।

### **1D অ্যারে (ভেক্টর)**

1D অ্যারে হলো সবচেয়ে সহজ রূপ, যা একটি সাধারণ লিস্টের মতো।

```python
arr1 = np.array([1, 2, 3])
```

### **2D অ্যারে (ম্যাট্রিক্স)**

একটি 2D অ্যারে হলো সারি (row) এবং কলাম (column) সহ একটি টেবিলের মতো। এটি মূলত একটি অ্যারের ভিতরে থাকা একাধিক অ্যারে।

```python
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
```

### **3D অ্যারে (টেনসর)**

একটি 3D অ্যারে-কে কয়েকটি **2D অ্যারের (ম্যাট্রিক্স)** একটি স্ট্যাক বা floor হিসাবে কল্পনা করা যেতে পারে। এটি ইমেজ প্রসেসিং-এর মতো ক্ষেত্রে খুব সাধারণ, যেখানে একটি ছবিকে তিনটি 2D অ্যারে হিসাবে প্রকাশ করা হয়: একটি লাল (Red) চ্যানেলের জন্য, একটি সবুজ (Green) চ্যানেলের জন্য এবং একটি নীল (Blue) চ্যানেলের জন্য।

আপনি এটিকে **গভীরতা (depth), সারি (row) এবং কলাম (column)** হিসেবে ভাবতে পারেন।

```python
arr3 = np.array([
    # প্রথম স্তর (বা ম্যাট্রিক্স)
    [
      [1, 2, 3],
      [4, 5, 6]
    ],
    # দ্বিতীয় স্তর (বা ম্যাট্রিক্স)
    [
      [7, 8, 9],
      [10, 11, 12]
    ]
])
```

-----

## **অ্যারের কিছু গুরুত্বপূর্ণ অ্যাট্রিবিউট**

আপনি একটি `ndarray`-এর বৈশিষ্ট্যগুলো তার অ্যাট্রিবিউট ব্যবহার করে জানতে পারেন।

### **`.ndim`**

এই অ্যাট্রিবিউটটি অ্যারের **ডাইমেনশন সংখ্যা** (বা অক্ষের সংখ্যা) দেখায়।

```python
print(f"arr1 ডাইমেনশন: {arr1.ndim}") # আউটপুট: 1
print(f"arr2 ডাইমেনশন: {arr2.ndim}") # আউটপুট: 2
print(f"arr3 ডাইমেনশন: {arr3.ndim}") # আউটপুট: 3
```

### **`.shape`**

এই অ্যাট্রিবিউটটি একটি **টাপল (tuple)** রিটার্ন করে যা প্রতিটি ডাইমেনশনে অ্যারের আকার দেখায়। এটি সবচেয়ে গুরুত্বপূর্ণ অ্যাট্রিবিউটগুলোর মধ্যে একটি।

```python
print(f"arr1-এর শেপ: {arr1.shape}")
print(f"arr2-এর শেপ: {arr2.shape}")
print(f"arr3-এর শেপ: {arr3.shape}")
```

**আউটপুট:**

```
arr1-এর শেপ: (3,)
arr2-এর শেপ: (2, 3)
arr3-এর শেপ: (2, 2, 3)
```

**শেপ টাপলটি কীভাবে পড়বেন:**

  * `(3,)`: এটি একটি **1D অ্যারে** যার একটিমাত্র অক্ষে **3টি উপাদান** আছে।
  * `(2, 3)`: এটি একটি **2D অ্যারে** যার **2টি সারি (row)** এবং **3টি কলাম (column)** আছে।
  * `(2, 2, 3)`: এটি একটি **3D অ্যারে**। এটিকে বাম থেকে ডানে পড়ুন: এতে **2টি স্তর/ম্যাট্রিক্স** আছে। প্রতিটি ম্যাট্রিক্সে **2টি সারি** এবং **3টি কলাম** আছে।

### **`.size`**

এই অ্যাট্রিবিউটটি অ্যারের **মোট উপাদান সংখ্যা** দেখায়। এটি শেপ টাপলের সংখ্যাগুলোর গুণফল।

```python
print(f"arr1-এর সাইজ: {arr1.size}") # আউটপুট: 3
print(f"arr2-এর সাইজ: {arr2.size}") # আউটপুট: 2 * 3 = 6
print(f"arr3-এর সাইজ: {arr3.size}") # আউটপুট: 2 * 2 * 3 = 12
```
___

### **`.dtype`**

**`.dtype`** (data type) অ্যাট্রিবিউটটি অত্যন্ত গুরুত্বপূর্ণ। এটি আপনাকে বলে দেয় যে NumPy অ্যারের ভিতরে ঠিক কোন ধরনের ডেটা সংরক্ষণ করা আছে। যেহেতু একটি NumPy অ্যারের প্রতিটি উপাদান অবশ্যই **একই ধরনের** হতে হবে, তাই এই অ্যাট্রিবিউটটি পুরো অ্যারের জন্য সেই টাইপটি নির্ধারণ করে।

এই সমজাতীয়তাই হলো NumPy-এর কার্যকারিতার মূল ভিত্তি। সঠিক ডেটা টাইপ জানার ফলে NumPy ডেটাগুলোকে একটি সুসংগঠিত উপায়ে সংরক্ষণ করতে পারে এবং গণনার জন্য অপ্টিমাইজড, নিম্ন-স্তরের ফাংশন ব্যবহার করতে পারে।

-----

### **NumPy কীভাবে `dtype` নির্ধারণ করে**

আপনি যখন কোনো টাইপ উল্লেখ না করে একটি NumPy অ্যারে তৈরি করেন, তখন NumPy ইনপুট ডেটা থেকে সবচেয়ে উপযুক্ত **`dtype` অনুমান (infer)** করে নেয়।

  * আপনি যদি শুধু পূর্ণসংখ্যা (integer) দেন, তবে এটি একটি ইন্টিজার টাইপ (যেমন `int64`) বেছে নেবে।
  * আপনি যদি একটিও ফ্লোটিং-পয়েন্ট নম্বর (দশমিক সংখ্যা) অন্তর্ভুক্ত করেন, তবে এটি ডেটার Verlust এড়াতে পুরো অ্যারেটিকে একটি ফ্লোট টাইপে (যেমন `float64`) রূপান্তর করবে।

চলুন আমাদের আগে তৈরি করা অ্যারেগুলো দেখি, যেগুলোতে শুধুমাত্র ইন্টিজার ছিল:

```python
import numpy as np

# স্বচ্ছতার জন্য আমাদের অ্যারেগুলো আবার লিখি
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(f"arr1-এর dtype: {arr1.dtype}")
print(f"arr2-এর dtype: {arr2.dtype}")
print(f"arr3-এর dtype: {arr3.dtype}")
```

**প্রত্যাশিত আউটপুট:**

```
arr1-এর dtype: int64
arr2-এর dtype: int64
arr3-এর dtype: int64
```

*(দ্রষ্টব্য: কিছু সিস্টেমে আউটপুট `int32` হতে পারে, তবে `int64` বেশি প্রচলিত। এটি একটি 64-বিটের ইন্টিজার বোঝায়।)*

-----

### **`dtype` নিজে নির্দিষ্ট করা ✍️**

আপনি অ্যারে তৈরির সময় NumPy-কে ডেটা টাইপ কী হবে তা স্পষ্টভাবে বলে দিতে পারেন। মেমরি ব্যবহার নিয়ন্ত্রণ করতে বা গণনার সঠিকতা নিশ্চিত করার জন্য এটি খুব দরকারি।

```python
# 64-বিট ফ্লোটিং-পয়েন্ট নম্বরের একটি অ্যারে তৈরি করা
float_arr = np.array([1, 2, 3], dtype=np.float64)

print(f"আসল অ্যারে: {arr1}, dtype: {arr1.dtype}")
print(f"নতুন ফ্লোট অ্যারে: {float_arr}, dtype: {float_arr.dtype}")
```

**আউটপুট:**

```
আসল অ্যারে: [1 2 3], dtype: int64
নতুন ফ্লোট অ্যারে: [1. 2. 3.], dtype: float64
```

লক্ষ্য করুন, `float_arr`-এর সংখ্যাগুলোকে ফ্লোট হিসেবে দেখানোর জন্য NumPy কীভাবে তাদের সাথে একটি দশমিক বিন্দু যোগ করেছে।

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
print(arr1)
print()

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2)
print()

arr3 = np.array([
    [
      [1, 2, 3],
      [4, 5, 6]
    ],
    [
      [7, 8, 9],
      [10, 11, 12]
    ],
])
print(arr3)
print()

# Types of Array
print(type(arr1))
print(type(arr2))
print(type(arr3))

[1 2 3]

[[1 2 3]
 [4 5 6]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### **Attributes**

In [ ]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [ ]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(3,)
(2, 3)
(2, 2, 3)


In [ ]:
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int64
int64
int64


In [ ]:
print(arr1.size)
print(arr2.size)
print(arr3.size)

3
6
12


# **NumPy Data Types: Upcasting and Type Control**

NumPy's efficiency comes from its strict, uniform data types. When you create an array, NumPy has a smart system for deciding the `dtype` for you, a process called **upcasting**.

-----

## **Automatic Type Inference: The Rule of Upcasting 🧠**

NumPy's primary rule is: **never lose information**. It will automatically "upcast" the data type of the entire array to the most general or precise type present in the input data.

1.  **All Integers → Integer Type**
    If all you provide are integers, NumPy creates an integer array. The specific kind (`int32` or `int64`) depends on your computer's operating system architecture (64-bit OS usually defaults to `int64`).

    ```python
    import numpy as np
    arr_i = np.array([1, 2, 3])
    print(arr_i.dtype) # Output: int64 (or int32 on some systems)
    ```

2.  **Integer + Float → Float Type**
    If the array contains even a single floating-point number, NumPy upcasts the *entire array* to a float type to preserve the decimal part.

    ```python
    arr_f = np.array([1, 2.3, 3])
    print(arr_f.dtype) # Output: float64
    ```

3.  **Anything + String → String Type**
    The string is the most general type. If a string is present, everything else is converted to a string.

    ```python
    arr_s = np.array([1, 2.3, "avc"])
    print(arr_s.dtype) # Output: <U32
    ```

    Here, `<U32` means a **Unicode string** with a maximum length of **32 characters**.

-----

## **A Note on Precision: `float32` vs. `float64`**

When NumPy upcasts to a float, it typically defaults to `float64`. This is known as **double-precision**.

  * **Single Precision (`float32`)**: Uses 32 bits of memory. It's faster and uses less memory but is less precise (about 7 decimal digits of precision).
  * **Double Precision (`float64`)**: Uses 64 bits of memory. It's the default because it is much more precise (about 15-16 decimal digits), which is crucial for scientific and financial calculations.

Think of it like a measuring tape. Single precision is like measuring to the nearest millimeter, while double precision is like measuring to the nearest micrometer.

-----

## **Manually Controlling `dtype` (and its Dangers ⚠️)**

You can force a specific `dtype` during array creation, but you must be careful.

### **1. "Safe" but Lossy Downcasting**

You can force a float array to be an integer array. This is considered "downcasting". NumPy will allow it, but it will **truncate** (cut off) the decimal part, leading to data loss.

```python
# The .3 in 2.3 will be lost
arr_downcast = np.array([1, 2.3, 3], dtype=np.int64)
print(arr_downcast)      # Output: [1 2 3]
print(arr_downcast.dtype) # Output: int64
```

### **2. Invalid Conversion Errors**

You cannot downcast when it's impossible. Trying to convert a non-numeric string like `"asd"` into a number will raise a `ValueError`.

```python
# This will cause an error!
# arr_error = np.array([1, 2.3, "asd"], dtype=np.int64)
# ValueError: invalid literal for int() with base 10: 'asd'
```

### **3. Out-of-Range Errors**

Specifying a smaller data type to save memory can be risky. If a value doesn't fit within the range of the specified type, you'll get an `OverflowError`. The range for `int8` is only **-128 to 127**.

```python
# This will cause an error because 422 is too large for int8
# arr_overflow = np.array([1, 2, 422], dtype=np.int8)
# OverflowError: Python int too large to convert to C long
```

-----

## **Changing Type After Creation: `.astype()`**

If you have an existing array, you can create a new copy with a different `dtype` using the `.astype()` method. This is a very common and useful operation.

```python
arr_float = np.array([1.1, 2.7, 3.5])
print(f"Original array: {arr_float}, dtype: {arr_float.dtype}")

# Create a new integer copy
arr_int = arr_float.astype(np.int32)
print(f"New array: {arr_int}, dtype: {arr_int.dtype}")
```

**Output:**

```
Original array: [1.1 2.7 3.5], dtype: float64
New array: [1 2 3], dtype: int32
```

Notice again that the decimal values were **truncated**, not rounded.

## **NumPy ডেটা টাইপ: আপকাস্টিং এবং টাইপ কন্ট্রোল**

NumPy-এর কার্যকারিতার মূলে রয়েছে এর কঠোর এবং অভিন্ন ডেটা টাইপ। আপনি যখন একটি অ্যারে তৈরি করেন, NumPy আপনার জন্য `dtype` নির্ধারণ করার জন্য একটি স্মার্ট সিস্টেম ব্যবহার করে, এই প্রক্রিয়াটিকে **আপকাস্টিং (upcasting)** বলা হয়।

-----

## **স্বয়ংক্রিয় টাইপ নির্ধারণ: আপকাস্টিং-এর নিয়ম 🧠**

NumPy-এর মূল নিয়ম হলো: **কখনোই ডেটা হারানো যাবে না**। এটি ইনপুট ডেটার মধ্যে সবচেয়ে সাধারণ বা সুনির্দিষ্ট (precise) টাইপটিকে বেছে নেয় এবং পুরো অ্যারের ডেটা টাইপকে সেই অনুযায়ী "আপকাস্ট" বা উন্নত করে।

1.  **সব ইন্টিজার → ইন্টিজার টাইপ**
    যদি আপনি শুধু ইন্টিজার দেন, NumPy একটি ইন্টিজার অ্যারে তৈরি করবে। নির্দিষ্ট ধরনটি (`int32` বা `int64`) আপনার কম্পিউটারের অপারেটিং সিস্টেম আর্কিটেকচারের উপর নির্ভর করে (64-বিট OS সাধারণত `int64` ব্যবহার করে)।

    ```python
    import numpy as np
    arr_i = np.array([1, 2, 3])
    print(arr_i.dtype) # আউটপুট: int64 (কিছু সিস্টেমে int32 হতে পারে)
    ```

2.  **ইন্টিজার + ফ্লোট → ফ্লোট টাইপ**
    অ্যারেতে যদি একটিও ফ্লোটিং-পয়েন্ট নম্বর (দশমিক সংখ্যা) থাকে, তবে NumPy দশমিক অংশটি রক্ষা করার জন্য *পুরো অ্যারেটিকে* একটি ফ্লোট টাইপে আপকাস্ট করে।

    ```python
    arr_f = np.array([1, 2.3, 3])
    print(arr_f.dtype) # আউটপুট: float64
    ```

3.  **যেকোনো কিছু + স্ট্রিং → স্ট্রিং টাইপ**
    স্ট্রিং হলো সবচেয়ে সাধারণ টাইপ। যদি একটি স্ট্রিং উপস্থিত থাকে, তবে বাকি সবকিছুকে স্ট্রিং-এ রূপান্তরিত করা হয়।

    ```python
    arr_s = np.array([1, 2.3, "avc"])
    print(arr_s.dtype) # আউটপুট: <U32
    ```

    এখানে `<U32` মানে হলো একটি **ইউনিকোড স্ট্রিং**, যার সর্বোচ্চ দৈর্ঘ্য **32 ক্যারেক্টার** হতে পারে।

-----

## **প্রিসিশন নোট: `float32` বনাম `float64`**

যখন NumPy একটি ফ্লোট টাইপে আপকাস্ট করে, তখন এটি সাধারণত `float64` ব্যবহার করে। এটিকে **ডাবল-প্রিসিশন (double-precision)** বলা হয়।

  * **সিঙ্গেল প্রিসিশন (`float32`)**: 32 বিট মেমরি ব্যবহার করে। এটি দ্রুত এবং কম মেমরি নেয় কিন্তু কম সুনির্দিষ্ট (প্রায় 7 দশমিক স্থান পর্যন্ত নির্ভুল)।
  * **ডাবল প্রিসিশন (`float64`)**: 64 বিট মেমরি ব্যবহার করে। এটি ডিফল্ট কারণ এটি অনেক বেশি সুনির্দিষ্ট (প্রায় 15-16 দশমিক স্থান পর্যন্ত নির্ভুল), যা বৈজ্ঞানিক এবং আর্থিক গণনার জন্য অত্যন্ত গুরুত্বপূর্ণ।

-----

## **`dtype` নিজে নিয়ন্ত্রণ করা (এবং এর বিপদ ⚠️)**

আপনি অ্যারে তৈরির সময় একটি নির্দিষ্ট `dtype` জোর করে সেট করতে পারেন, তবে আপনাকে সতর্ক থাকতে হবে।

### **১. "নিরাপদ" কিন্তু ডেটা হারানো ডাউনকাস্টিং**

আপনি একটি ফ্লোট অ্যারে-কে ইন্টিজার অ্যারেতে রূপান্তর করতে পারেন। একে "ডাউনকাস্টিং" বলা হয়। NumPy এটি করতে দেবে, কিন্তু এটি দশমিক অংশটি **ট্রাঙ্কেট (truncate)** বা কেটে ফেলবে, যার ফলে ডেটা হারিয়ে যাবে।

```python
# 2.3 এর .3 অংশটি হারিয়ে যাবে
arr_downcast = np.array([1, 2.3, 3], dtype=np.int64)
print(arr_downcast)      # আউটপুট: [1 2 3]
print(arr_downcast.dtype) # আউটপুট: int64
```

### **২. ValueError**

যখন রূপান্তর অসম্ভব, তখন আপনি ডাউনকাস্ট করতে পারবেন না। `"asd"`-এর মতো একটি নন-নিউমেরিক স্ট্রিংকে নম্বরে রূপান্তর করার চেষ্টা করলে একটি `ValueError` দেখাবে।

```python
# এটি এরর দেবে!
# arr_error = np.array([1, 2.3, "asd"], dtype=np.int64)
# ValueError: invalid literal for int() with base 10: 'asd'
```

### **৩. OverflowError**

মেমরি বাঁচানোর জন্য ছোট ডেটা টাইপ নির্দিষ্ট করা ঝুঁকিপূর্ণ হতে পারে। যদি কোনো মান নির্দিষ্ট টাইপের সীমার মধ্যে না থাকে, তবে আপনি একটি `OverflowError` পাবেন। `int8`-এর সীমা শুধুমাত্র **-128 থেকে 127** পর্যন্ত।

```python
# এটি এরর দেবে কারণ 422 সংখ্যাটি int8-এর জন্য খুব বড়
# arr_overflow = np.array([1, 2, 422], dtype=np.int8)
# OverflowError: Python int too large to convert to C long
```

-----

## **তৈরির পরে টাইপ পরিবর্তন: `.astype()`**

যদি আপনার কাছে একটি অ্যারে থাকে, তবে আপনি `.astype()` মেথড ব্যবহার করে ভিন্ন `dtype` সহ একটি নতুন কপি তৈরি করতে পারেন। এটি একটি খুব সাধারণ এবং দরকারী অপারেশন।

```python
arr_float = np.array([1.1, 2.7, 3.5])
print(f"আসল অ্যারে: {arr_float}, dtype: {arr_float.dtype}")

# একটি নতুন ইন্টিজার কপি তৈরি করা
arr_int = arr_float.astype(np.int32)
print(f"নতুন অ্যারে: {arr_int}, dtype: {arr_int.dtype}")
```

**আউটপুট:**

```
আসল অ্যারে: [1.1 2.7 3.5], dtype: float64
নতুন অ্যারে: [1 2 3], dtype: int32
```

এখানেও লক্ষ্য করুন যে দশমিক মানগুলো রাউন্ড না হয়ে **ট্রাঙ্কেট** বা কেটে ফেলা হয়েছে।

In [ ]:
arr = np.array([1,2,3])
print(arr.dtype)

int64


In [ ]:
arr = np.array([1.2,2.3,3.5])
print(arr.dtype)

float64


In [ ]:
arr_f = np.array([1,2.3,3])
print(arr_f.dtype)

float64


In [ ]:
arr_s = np.array([1,2.3,3,"avc"])
print(arr_s.dtype)

<U32


In [ ]:

arr_f = np.array([1,2.3,3], dtype=np.uint32)
print(arr_f.dtype)
print(arr_f)

uint32
[1 2 3]


In [ ]:
# Throw error
# arr_f = np.array([1,2.3,"asd"],dtype=np.int64)
# print(arr_f.dtype)


In [ ]:
arr_f = np.array([1,2.3,3])
print(arr_f.dtype)

arr_f = arr.astype(np.int32)
print(arr_f.dtype)


float64
int32


In [ ]:
# show erro
#rr= np.array([1,2,3.5,[1,2,4],"anv"])


In [ ]:
arr= np.array([1,2,3.5,"anv"])
print(arr.dtype)

<U32


# **Creating an `ndarray` from Existing Data**

You can easily create NumPy arrays from standard Python data structures like lists, tuples, sets, and dictionaries. However, there are important rules and behaviors to understand for each.

-----

### **1. From a Python `list` 📜**

This is the most common way to create an `ndarray`.

### **1D Lists**

NumPy handles **upcasting** automatically to preserve data. If a list contains a mix of types, NumPy will choose the most general type for the entire array.

```python
import numpy as np

# A float value forces the whole array to be float64
lst = [10, 20, 30, 40, 40.5]
arr = np.array(lst)

print(f"Array: {arr}")
print(f"Dtype: {arr.dtype}")
```

**Output:**

```
Array: [10.  20.  30.  40.  40.5]
Dtype: float64
```

You can manually set the `dtype` during creation or change it later with `.astype()`, but be aware of potential data loss (truncation).

### **2D Lists (Matrices)**

For multi-dimensional arrays, NumPy requires a consistent, **rectangular shape**.

**Rule:** Every inner list must have the **same number of elements**.

```python
# This will cause an error because the lists have different lengths
two_d_list_bad = [
    [1, 2, 3],
    [4, 5, 6, 7] # This list is longer
]
# np.array(two_d_list_bad) -> ValueError
```

### **The `ValueError` from Ragged Arrays ⚠️**

When a list contains a mix of single items and other sequences (like another list), it's called a **"ragged" array**. Modern NumPy will raise a `ValueError` because it cannot create a simple, rectangular grid.

```python
# This is a "ragged" list
mixed_lst = [10,  40.5, True, "hello", [1,2,3]]

# This will raise a ValueError.
# arr = np.array(mixed_lst)
```

**Error:** `ValueError: setting an array element with a sequence.`

**Solution:** You can force this to work by explicitly setting `dtype=object`. This tells NumPy to create a generic container of Python objects, but you **lose all performance benefits** and the ability to do math operations. Use it sparingly.

```python
arr_object = np.array(mixed_lst, dtype=object)
print(f"Object array: {arr_object}, dtype: {arr_object.dtype}")
```

**Output:**

```
Object array: [10 40.5 True 'hello' list([1, 2, 3])], dtype: object
```

-----

## **2. From a Python `tuple` 📦**

Creating an array from a tuple works **exactly like creating one from a list**. All the same rules of upcasting and shape uniformity apply.

```python
mat_tu = (
          (1, 2, 3),
          (4, 5, 6),
          (7, 8, 9)
         )
arr = np.array(mat_tu)

print(f"Array from tuple:\n{arr}")
print(f"Shape: {arr.shape}")
```

**Output:**

```
Array from tuple:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
```

-----

## **3. From a Python `set` 🌀**

Directly converting a set to an `ndarray` is problematic. Because sets are **unordered**, NumPy doesn't try to infer a numeric type. Instead, it creates a single-element array of `dtype=object`.

**Solution:** First, convert the set to a **`list`** or **`tuple`**.

```python
st = {1, 2, 3, 4, 5}

# Wrong way - creates an object array
arr_wrong = np.array(st)
print(f"Wrong Way Dtype: {arr_wrong.dtype}") # Output: object

# Correct way
arr_correct = np.array(list(st))
print(f"Correct Way Dtype: {arr_correct.dtype}") # Output: int64
```

To create a 2D array, you can use a set of tuples and convert it to a list first.

```python
st_2d = {(1,2,3), (4,5,6)}
arr_2d_from_set = np.array(list(st_2d))
print(f"\n2D Array from set of tuples:\n{arr_2d_from_set}")
```

-----

## **4. From a Python `dict` 🔑**

A dictionary has a key-value structure, so it cannot be directly converted. You must first extract the `.keys()`, `.values()`, or `.items()` and then convert those to a `list`.

```python
dic = {'a': 10, 'b': 20, 'c': 30}

# Convert keys to an array
keys_arr = np.array(list(dic.keys()))
print(f"Keys Array: {keys_arr}")

# Convert values to an array
values_arr = np.array(list(dic.values()))
print(f"Values Array: {values_arr}")

# Convert items (key-value pairs) to a 2D array
items_arr = np.array(list(dic.items()))
print(f"\nItems Array:\n{items_arr}")
print(f"Items Dtype: {items_arr.dtype}") # Dtype is string due to upcasting
```

**Output:**

```
Keys Array: ['a' 'b' 'c']
Values Array: [10 20 30]

Items Array:
[['a' '10']
 ['b' '20']
 ['c' '30']]
Items Dtype: <U21
```

___


## **বিদ্যমান ডেটা থেকে `ndarray` তৈরি করা**

আপনি পাইথনের সাধারণ ডেটা স্ট্রাকচার যেমন লিস্ট, টুপল, সেট এবং ডিকশনারি থেকে সহজেই NumPy অ্যারে তৈরি করতে পারেন। তবে, প্রতিটির জন্য কিছু গুরুত্বপূর্ণ নিয়ম এবং আচরণ বোঝা প্রয়োজন।

-----

## **১. পাইথন `list` থেকে 📜**

`ndarray` তৈরি করার এটিই সবচেয়ে প্রচলিত উপায়।

### **1D লিস্ট**

ডেটা রক্ষা করার জন্য NumPy স্বয়ংক্রিয়ভাবে **আপকাস্টিং (upcasting)** পরিচালনা করে। যদি একটি লিস্টে বিভিন্ন ধরণের ডেটা মিশ্রিত থাকে, তবে NumPy পুরো অ্যারের জন্য সবচেয়ে সাধারণ টাইপটি বেছে নেয়।

```python
import numpy as np

# একটি ফ্লোট মান পুরো অ্যারেটিকে float64 বানিয়ে দেবে
lst = [10, 20, 30, 40, 40.5]
arr = np.array(lst)

print(f"অ্যারে: {arr}")
print(f"Dtype: {arr.dtype}")
```

**আউটপুট:**

```
অ্যারে: [10.  20.  30.  40.  40.5]
Dtype: float64
```

আপনি অ্যারে তৈরির সময় `dtype` নিজে সেট করতে পারেন অথবা পরে `.astype()` দিয়ে পরিবর্তন করতে পারেন, তবে এতে ডেটা হারানোর (truncation) সম্ভাবনা থাকে।

### **2D লিস্ট (ম্যাট্রিক্স)**

বহুমাত্রিক (multi-dimensional) অ্যারের জন্য NumPy-কে একটি সামঞ্জস্যপূর্ণ, **আয়তক্ষেত্রাকার (rectangular) আকৃতি** প্রয়োজন।

**নিয়ম:** প্রতিটি ভেতরের লিস্টে অবশ্যই **একই সংখ্যক উপাদান** থাকতে হবে।

```python
# এটি এরর দেবে কারণ লিস্টগুলোর দৈর্ঘ্য ভিন্ন
two_d_list_bad = [
    [1, 2, 3],
    [4, 5, 6, 7] # এই লিস্টটি দীর্ঘ
]
# np.array(two_d_list_bad) -> ValueError
```

### **র‍্যাগড অ্যারে (Ragged Arrays) থেকে `ValueError` ⚠️**

যখন একটি লিস্টে একক আইটেম এবং অন্যান্য সিকোয়েন্স (যেমন আরেকটি লিস্ট) মিশ্রিত থাকে, তখন তাকে **"র‍্যাগড" অ্যারে** বলা হয়। আধুনিক NumPy এক্ষেত্রে একটি `ValueError` দেখায় কারণ এটি একটি সহজ, আয়তক্ষেত্রাকার গ্রিড তৈরি করতে পারে না।

```python
# এটি একটি "র‍্যাগড" লিস্ট
mixed_lst = [10,  40.5, True, "hello", [1,2,3]]

# এটি একটি ValueError দেবে
# arr = np.array(mixed_lst)
```

**এরর:** `ValueError: setting an array element with a sequence.`

**সমাধান:** আপনি `dtype=object` স্পষ্টভাবে সেট করে এটি কাজ করাতে পারেন। এটি NumPy-কে পাইথন অবজেক্টগুলোর একটি সাধারণ কন্টেইনার তৈরি করতে বলে, কিন্তু এর ফলে আপনি **পারফরম্যান্সের সমস্ত সুবিধা হারাবেন** এবং গাণিতিক অপারেশন করতে পারবেন না। তাই এটি খুব কম ব্যবহার করা উচিত।

```python
arr_object = np.array(mixed_lst, dtype=object)
print(f"অবজেক্ট অ্যারে: {arr_object}, dtype: {arr_object.dtype}")
```

**আউটপুট:**

```
অবজেক্ট অ্যারে: [10 40.5 True 'hello' list([1, 2, 3])], dtype: object
```

-----

## **২. পাইথন `tuple` থেকে 📦**

একটি টুপল থেকে অ্যারে তৈরি করা **ঠিক একটি লিস্ট থেকে অ্যারে তৈরির মতোই** কাজ করে। আপকাস্টিং এবং আকৃতির সামঞ্জস্যের সমস্ত নিয়ম এখানেও প্রযোজ্য।

```python
mat_tu = (
          (1, 2, 3),
          (4, 5, 6),
          (7, 8, 9)
         )
arr = np.array(mat_tu)

print(f"টুপল থেকে অ্যারে:\n{arr}")
print(f"Shape: {arr.shape}")
```

**আউটপুট:**

```
টুপল থেকে অ্যারে:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
```

-----

## **৩. পাইথন `set` থেকে 🌀**

সরাসরি একটি সেটকে `ndarray`-তে রূপান্তর করা একটি সমস্যা। কারণ সেট **অগোছালো (unordered)**, তাই NumPy একটি নিউমেরিক টাইপ অনুমান করার চেষ্টা করে না। পরিবর্তে, এটি পুরো সেটটিকে ধারণ করে একটি একক-উপাদানের `dtype=object` অ্যারে তৈরি করে।

**সমাধান:** প্রথমে সেটটিকে একটি **`list`** বা **`tuple`**-এ রূপান্তর করুন।

```python
st = {1, 2, 3, 4, 5}

# ভুল পদ্ধতি - একটি অবজেক্ট অ্যারে তৈরি করে
arr_wrong = np.array(st)
print(f"ভুল পদ্ধতির Dtype: {arr_wrong.dtype}") # আউটপুট: object

# সঠিক পদ্ধতি
arr_correct = np.array(list(st))
print(f"সঠিক পদ্ধতির Dtype: {arr_correct.dtype}") # আউটপুট: int64
```

একটি 2D অ্যারে তৈরি করতে, আপনি টুপলের একটি সেট ব্যবহার করতে পারেন এবং প্রথমে সেটিকে একটি লিস্টে রূপান্তর করতে পারেন।

```python
st_2d = {(1,2,3), (4,5,6)}
arr_2d_from_set = np.array(list(st_2d))
print(f"\nটুপলের সেট থেকে 2D অ্যারে:\n{arr_2d_from_set}")
```

-----

## **৪. পাইথন `dict` থেকে 🔑**

একটি ডিকশনারিতে কী-ভ্যালু (key-value) স্ট্রাকচার থাকায় এটিকে সরাসরি রূপান্তর করা যায় না। আপনাকে প্রথমে `.keys()`, `.values()`, বা `.items()` বের করে সেগুলোকে একটি `list`-এ রূপান্তর করতে হবে।

```python
dic = {'a': 10, 'b': 20, 'c': 30}

# কী (keys) থেকে অ্যারে
keys_arr = np.array(list(dic.keys()))
print(f"কী অ্যারে: {keys_arr}")

# ভ্যালু (values) থেকে অ্যারে
values_arr = np.array(list(dic.values()))
print(f"ভ্যালু অ্যারে: {values_arr}")

# আইটেম (items) থেকে 2D অ্যারে
items_arr = np.array(list(dic.items()))
print(f"\nআইটেম অ্যারে:\n{items_arr}")
print(f"আইটেম Dtype: {items_arr.dtype}") # আপকাস্টিং-এর কারণে Dtype স্ট্রিং হবে
```

**আউটপুট:**

```
কী অ্যারে: ['a' 'b' 'c']
ভ্যালু অ্যারে: [10 20 30]

আইটেম অ্যারে:
[['a' '10']
 ['b' '20']
 ['c' '30']]
আইটেম Dtype: <U21
```

In [3]:
import numpy as np

lst = [10, 20, 30, 40, 40.5]
arr = np.array(lst)
print(type(arr))
print(arr.dtype)
print(arr.ndim)

# arr = arr.astype(np.int32)
# print(arr.dtype)

<class 'numpy.ndarray'>
float64
1
int32


In [4]:
lst = [10, 20, 30, 40, 40.5]
arr = np.array(lst, dtype=np.int32)
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int32


In [5]:
mixed_lst = [10,  40.5, True, "hello"]
arr = np.array(mixed_lst)
print(type(arr))
print(arr.dtype)
print(arr.ndim)

<class 'numpy.ndarray'>
<U32
1


In [9]:
#ValueError
# mixed_lst = [10,  40.5, True, "hello", [1,2,3]]
# arr = np.array(mixed_lst)

In [25]:
two_d_list = [
    [1, 2, 3],
    [4, 5, 6]
]

arr = np.array(two_d_list)
print(type(arr))
print(arr.dtype)
print(arr.ndim)

<class 'numpy.ndarray'>
int64
2


In [19]:
# ValueError
# two_d_list = [
#     [1, 2, 3],
#     [4, 5, 6, 7]
# ]
# two_d_array = np.array(two_d_list)

In [27]:
tu = (1,2,3)
arr = np.array(tu)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int64
1


In [28]:
mat_tu = (
          (1,2,3),
          (4,5,6),
          (7,8,9)
          )
arr = np.array(mat_tu)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
2


In [29]:
mat_tu = (
          (1,2,3),
          (4,5,6),
          (7,8,9)
          )
arr = np.array(mat_tu, dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)

arr = arr.astype(np.int8)
print(arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int32
2
int8


In [31]:
# st = {1,2,3,4,5}
# arr = np.array(st, dtype=np.int32)

In [32]:
st = {1,2,3,4,5}
arr = np.array(st)
print(arr)
print(type(arr))
print(arr.dtype)


{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>
object


In [34]:
st = {1,2,3,4,5}
arr = np.array(list(st), dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype)


[1 2 3 4 5]
<class 'numpy.ndarray'>
int32


In [38]:
st_2d = {(1,2,3),(4,5,6)}
arr = np.array(list(st_2d))
print(arr)
print(type(arr))
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int8


In [49]:
dic = {'a':10, 'b':20, 'c':30}
keys = dic.keys()

values = dic.values()

key_value = dic.items()

# It not possible directly
keys_arr = np.array(keys)
print(keys_arr.dtype) #object

# firstly we need to convert list or tuple then make ndarry
keys_arr = np.array(list(keys))
print(keys_arr.dtype) #int64
print(keys_arr)
print()

values_arr = np.array(list(values))
print(values_arr.dtype) #int64
print(values_arr)
print()

key_value_arr = np.array(list(key_value))
print(key_value_arr.dtype) #object
print(key_value_arr)



object
<U1
['a' 'b' 'c']

int64
[10 20 30]

<U21
[['a' '10']
 ['b' '20']
 ['c' '30']]


# **Creating an `ndarray` From Scratch**

NumPy provides several convenient functions to create arrays from scratch without needing an existing Python data structure. These are highly efficient for initializing arrays of a specific size with placeholder values.

-----

## **1. `np.zeros` and `np.zeros_like`**

The `np.zeros()` function creates an array of a given shape, filling it entirely with **zeros**.

  * **Default `dtype`**: By default, the array is filled with floating-point zeros (`0.`) and has a `dtype` of `float64`.
  * **Shape**: The first argument is the shape, provided as an integer for 1D arrays or a tuple for multi-dimensional arrays.

<!-- end list -->

```python
import numpy as np

# 1D array of zeros (float by default)
arr_1d = np.zeros(3)
print(f"1D Zeros:\n{arr_1d}\nDtype: {arr_1d.dtype}\n")

# 2D array of zeros, with dtype specified as integer
arr_2d = np.zeros((2, 3), dtype=np.int32)
print(f"2D Integer Zeros:\n{arr_2d}\nDtype: {arr_2d.dtype}")
```

### **`np.zeros_like()`**

This is a handy function to create a new array of zeros that has the **exact same shape and `dtype`** as an existing array.

```python
arr_existing = np.array([[1, 2], [3, 4]])

arr_zeros_like = np.zeros_like(arr_existing)
print(f"\nZeros array like existing one:\n{arr_zeros_like}")
print(f"Shape: {arr_zeros_like.shape}, Dtype: {arr_zeros_like.dtype}")
```

-----

## **2. `np.ones` and `np.ones_like`**

This works exactly like `np.zeros()`, but it fills the array with **ones** (`1.`) instead.

```python
# 2D array of ones (float by default)
arr_2d_ones = np.ones((2, 3))
print(f"2D Ones:\n{arr_2d_ones}\nDtype: {arr_2d_ones.dtype}\n")

# 3D array of ones using ones_like
arr3_ones_like = np.ones_like(arr_zeros_like) # Using the array from the previous example
print(f"Ones array like the zeros one:\n{arr3_ones_like}")
print(f"Shape: {arr3_ones_like.shape}, Dtype: {arr3_ones_like.dtype}")
```

-----

## **3. `np.empty` and `np.empty_like`**

The `np.empty()` function creates an array of a given shape **without initializing its entries to any particular value**.

**Important Note:** The values you see in an `empty` array are not truly random. They are whatever "garbage" data was already present in that memory location. This function is slightly faster than `zeros` or `ones` and is useful only when you plan to immediately overwrite every element in the array yourself.

```python
# Create a 2x3 empty array. The values will be unpredictable.
arr_empty = np.empty((2, 3))
print(f"Empty Array (values are arbitrary):\n{arr_empty}")
```

-----

## **4. `np.full` and `np.full_like`**

This function gives you more control by allowing you to create an array of a specific shape filled with any **`fill_value`** you choose.

  * **Arguments**: It takes two main arguments: `shape` and `fill_value`.
  * **`dtype` Inference**: NumPy infers the `dtype` from the type of the `fill_value`.

<!-- end list -->

```python
# Create a 2x3 array filled with the integer 5
arr_full_int = np.full((2, 3), 5)
print(f"Full array with integers:\n{arr_full_int}\nDtype: {arr_full_int.dtype}\n")

# Create a 2x3 array filled with boolean True
arr_full_bool = np.full((2, 3), True)
print(f"Full array with booleans:\n{arr_full_bool}\nDtype: {arr_full_bool.dtype}\n")

# Create a 2x3 array filled with infinity
arr_full_inf = np.full((2, 3), np.inf)
print(f"Full array with infinity:\n{arr_full_inf}\nDtype: {arr_full_inf.dtype}\n")
```

The `np.full_like()` variant creates a new array with the shape and `dtype` of an existing array, but fills it with a new specified value.

```python
arr_existing = np.array([[1, 2], [3, 4]])

# Create a new array like arr_existing but filled with -1
arr_full_like = np.full_like(arr_existing, -1)
print(f"Full_like array:\n{arr_full_like}")
```


অবশ্যই\! আপনার জন্য সম্পূর্ণ নোটটি বাংলাতে নিচে দেওয়া হলো।

___

## **Creating an ndarray From Scratch(Bangla)**

বিদ্যমান কোনো পাইথন ডেটা স্ট্রাকচার ছাড়াই শুরু থেকে অ্যারে তৈরি করার জন্য NumPy বেশ কিছু সুবিধাজনক ফাংশন সরবরাহ করে। একটি নির্দিষ্ট আকারের অ্যারে ইনিশিয়ালাইজ করার জন্য এগুলো অত্যন্ত কার্যকর।

-----

## **১. `np.zeros` এবং `np.zeros_like`**

`np.zeros()` ফাংশনটি একটি নির্দিষ্ট আকারের অ্যারে তৈরি করে, যা সম্পূর্ণরূপে **শূন্য (`0`)** দিয়ে পূর্ণ থাকে।

  * **ডিফল্ট `dtype`**: ডিফল্টভাবে, অ্যারেটি ফ্লোটিং-পয়েন্ট শূন্য (`0.`) দিয়ে পূর্ণ থাকে এবং এর `dtype` হয় `float64`।
  * **শেপ (Shape)**: প্রথম আর্গুমেন্ট হলো শেপ, যা 1D অ্যারের জন্য একটি ইন্টিজার বা বহুমাত্রিক (multi-dimensional) অ্যারের জন্য একটি টুপল হিসেবে দেওয়া হয়।

<!-- end list -->

```python
import numpy as np

# 1D শূন্যের অ্যারে (ডিফল্টভাবে ফ্লোট)
arr_1d = np.zeros(3)
print(f"1D Zeros:\n{arr_1d}\nDtype: {arr_1d.dtype}\n")

# 2D শূন্যের অ্যারে, যেখানে dtype ইন্টিজার হিসেবে নির্দিষ্ট করা হয়েছে
arr_2d = np.zeros((2, 3), dtype=np.int32)
print(f"2D Integer Zeros:\n{arr_2d}\nDtype: {arr_2d.dtype}")
```

### **`np.zeros_like()`**

এটি একটি সুবিধাজনক ফাংশন যা একটি নতুন শূন্যের অ্যারে তৈরি করে, যার **শেপ এবং `dtype`** হুবহু বিদ্যমান একটি অ্যারের মতো হয়।

```python
arr_existing = np.array([[1, 2], [3, 4]])

arr_zeros_like = np.zeros_like(arr_existing)
print(f"\nবিদ্যমান অ্যারের মতো শূন্যের অ্যারে:\n{arr_zeros_like}")
print(f"Shape: {arr_zeros_like.shape}, Dtype: {arr_zeros_like.dtype}")
```

-----

## **২. `np.ones` এবং `np.ones_like`**

এটি `np.zeros()`-এর মতোই কাজ করে, কিন্তু এটি অ্যারেটিকে **এক (`1`)** দিয়ে পূর্ণ করে।

```python
# 2D একের অ্যারে (ডিফল্টভাবে ফ্লোট)
arr_2d_ones = np.ones((2, 3))
print(f"2D Ones:\n{arr_2d_ones}\nDtype: {arr_2d_ones.dtype}\n")

# ones_like ব্যবহার করে 3D একের অ্যারে
# আগের উদাহরণ থেকে অ্যারে ব্যবহার করে
arr3_ones_like = np.ones_like(arr_zeros_like)
print(f"শূন্যের অ্যারের মতো একের অ্যারে:\n{arr3_ones_like}")
print(f"Shape: {arr3_ones_like.shape}, Dtype: {arr3_ones_like.dtype}")
```

-----

## **৩. `np.empty` এবং `np.empty_like`**

`np.empty()` ফাংশনটি কোনো নির্দিষ্ট মান দিয়ে উপাদানগুলোকে ইনিশিয়ালাইজ না করেই একটি নির্দিষ্ট আকারের অ্যারে তৈরি করে।

**গুরুত্বপূর্ণ নোট:** একটি `empty` অ্যারেতে যে মানগুলো দেখা যায়, সেগুলো সত্যি সত্যি র‍্যান্ডম নয়। এগুলো হলো সেই মেমরি লোকেশনে আগে থেকে থাকা "গার্বেজ" ডেটা। এই ফাংশনটি `zeros` বা `ones`-এর চেয়ে কিছুটা দ্রুত এবং শুধুমাত্র তখনই উপযোগী যখন আপনি অ্যারের প্রতিটি উপাদানকে உடனடியாக নিজে ওভাররাইট করার পরিকল্পনা করেন।

```python
# একটি 2x3 empty অ্যারে তৈরি করা হলো। এর মানগুলো অনির্ predictable হবে।
arr_empty = np.empty((2, 3))
print(f"Empty Array (মানগুলো ইচ্ছামতো হতে পারে):\n{arr_empty}")
```

-----

## **৪. `np.full` এবং `np.full_like`**

এই ফাংশনটি আপনাকে আপনার পছন্দের যেকোনো **`fill_value`** দিয়ে একটি নির্দিষ্ট আকারের অ্যারে তৈরি করার সুবিধা দেয়।

  * **আর্গুমেন্টস**: এটি দুটি প্রধান আর্গুমেন্ট নেয়: `shape` এবং `fill_value`।
  * **`dtype` অনুমান**: NumPy `fill_value`-এর টাইপ থেকে `dtype` অনুমান করে নেয়।

<!-- end list -->

```python
# ইন্টিজার 5 দিয়ে পূর্ণ একটি 2x3 অ্যারে
arr_full_int = np.full((2, 3), 5)
print(f"ইন্টিজার দিয়ে পূর্ণ অ্যারে:\n{arr_full_int}\nDtype: {arr_full_int.dtype}\n")

# বুলিয়ান True দিয়ে পূর্ণ একটি 2x3 অ্যারে
arr_full_bool = np.full((2, 3), True)
print(f"বুলিয়ান দিয়ে পূর্ণ অ্যারে:\n{arr_full_bool}\nDtype: {arr_full_bool.dtype}\n")

# ইনফিনিটি দিয়ে পূর্ণ একটি 2x3 অ্যারে
arr_full_inf = np.full((2, 3), np.inf)
print(f"ইনফিনিটি দিয়ে পূর্ণ অ্যারে:\n{arr_full_inf}\nDtype: {arr_full_inf.dtype}\n")
```

`np.full_like()` ভেরিয়েন্টটি একটি বিদ্যমান অ্যারের শেপ এবং `dtype` অনুযায়ী একটি নতুন অ্যারে তৈরি করে, কিন্তু সেটিকে একটি নতুন নির্দিষ্ট মান দিয়ে পূর্ণ করে।

```python
arr_existing = np.array([[1, 2], [3, 4]])

# arr_existing-এর মতো একটি নতুন অ্যারে তৈরি করা হলো যা -1 দিয়ে পূর্ণ
arr_full_like = np.full_like(arr_existing, -1)
print(f"Full_like অ্যারে:\n{arr_full_like}")
```

###**np.zeros**

In [62]:
# Make 1d array with value 0
arr = np.zeros(3)
print(arr)
print(arr.dtype) # by default it will be float

[0. 0. 0.]
float64


In [63]:
# Make 2d arrays with value 0
arr = np.zeros((2,3))
print(arr)
print(arr.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [64]:
# make 3d array with value 0
arr = np.zeros((2,3,4))
print(arr)
print(arr.dtype)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
float64


In [65]:
#we can determine datatype when creaing or after creating to int
arr = np.zeros((3,3), dtype=np.int32)
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int32


In [68]:
# We can make nd array as like previous array with value 0
arr3 = np.array([
    [
      [1, 2, 3],
      [4, 5, 6]
    ],
    [
      [7, 8, 9],
      [10, 11, 12]
    ],
])

print(arr3)
print(arr3.dtype)
print(arr3.ndim)

print()

arr3_zeros = np.zeros_like(arr3)
print(arr3_zeros)
print(arr3_zeros.dtype)
print(arr3_zeros.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
int64
3

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
int64
3


### **np.ones**

In [69]:
# Make 1d array with value 1
arr = np.ones(3)
print(arr)
print(arr.dtype) # by default it will be float

[1. 1. 1.]
float64


In [70]:
# Make 2d arrays with value 1
arr = np.ones((2,3))
print(arr)
print(arr.dtype)

[[1. 1. 1.]
 [1. 1. 1.]]
float64


In [71]:
# make 3d array with value 1
arr = np.ones((2,3,4))
print(arr)
print(arr.dtype)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
float64


In [72]:
#we can determine datatype when creaing or after creating to int
arr = np.ones((3,3), dtype=np.int32)
print(arr)
print(arr.dtype)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
int32


In [73]:
# We can make nd array as like previous array with value 0
arr3 = np.array([
    [
      [1, 2, 3],
      [4, 5, 6]
    ],
    [
      [7, 8, 9],
      [10, 11, 12]
    ],
])

print(arr3)
print(arr3.dtype)
print(arr3.ndim)

print()

arr3_ones = np.ones_like(arr3)
print(arr3_ones)
print(arr3_ones.dtype)
print(arr3_ones.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
int64
3

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
int64
3


### **np.empty**

In [81]:
# Make 1d array with random value
arr = np.empty(3)
print(arr)
print(arr.dtype) # by default it will be float


[7.74860419e-304 7.74860419e-304 7.74860419e-304]
float64


In [84]:

# Make 2d arrays with random value
arr = np.empty((2,3))
print(arr)
print(arr.dtype)

[[1. 1. 1.]
 [1. 1. 1.]]
float64


In [83]:

# make 3d array with random value
arr = np.empty((2,3,4))
print(arr)
print(arr.dtype)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
float64


In [86]:
#we can determine datatype when creaing or after creating to int
arr = np.empty((3,3), dtype=np.int32)
print(arr)
print(arr.dtype)

[[453752996         0         0]
 [        0        99       116]
 [      108       121  11665408]]
int32


In [88]:
# We can make nd array as like previous array with random value
arr3 = np.array([
    [
      [1, 2, 3],
      [4, 5, 6]
    ],
    [
      [7, 8, 9],
      [10, 11, 12]
    ],
])

print(arr3)
print(arr3.dtype)
print(arr3.ndim)

print()

arr3_random = np.empty_like(arr3)
print(arr3_random)
print(arr3_random.dtype)
print(arr3_random.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
int64
3

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
int64
3


### **np.full**

In [89]:
arr = np.full((2,3), 5)
print(arr)
print(arr.dtype)

[[5 5 5]
 [5 5 5]]
int64


In [90]:
arr = np.full((2,3), True)
print(arr)
print(arr.dtype)

[[ True  True  True]
 [ True  True  True]]
bool


In [92]:
arr = np.full((2,3), np.inf)
print(arr)
print(arr.dtype)

[[inf inf inf]
 [inf inf inf]]
float64


In [94]:
arr3 = np.array([
    [
      [1, 2, 3],
      [4, 5, 6]
    ],
    [
      [7, 8, 9],
      [10, 11, 12]
    ],
], dtype=np.float64)

arr3_full = np.full_like(arr3, np.inf)
print(arr3_full)
print(arr3_full.dtype)
print(arr3_full.ndim)
#

[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
float64
3


# **`ndarray` Generation with Random Values 🎲**

Generating random data is a fundamental task in Machine Learning and Data Science. It's used for creating synthetic datasets, initializing model parameters (like the weights in a neural network), and evaluating model performance through random sampling. NumPy's `random` module provides a powerful suite of tools for this.

-----

## **1. `np.random.rand()`**

This function creates an array of a given shape and populates it with random samples from a **uniform distribution** over the interval **[0, 1)**. This means every number between 0 (inclusive) and 1 (exclusive) has an equal chance of being generated.

**Syntax Note:** Unlike other functions, you pass the dimensions as separate arguments, not as a tuple. `np.random.rand(d0, d1, ...)`

```python
import numpy as np

# Create a 1D array of 4 random floats
arr_1d = np.random.rand(4)
print(f"1D Random Array:\n{arr_1d}\n")

# Create a 2D array (4 rows, 3 columns)
arr_2d = np.random.rand(4, 3)
print(f"2D Random Array:\n{arr_2d}\n")

# Create a 3D array
arr_3d = np.random.rand(2, 4, 3)
print(f"3D Random Array:\n{arr_3d}")
```

The `dtype` of arrays created with `rand()` is always `float64`.

-----

## **2. `np.random.randint()`**

This function generates an array of a given shape filled with random **integers** from a specified range.

**Syntax:** `np.random.randint(low, high=None, size=None)`

  * If only `low` is provided, the range is `[0, low)`.
  * If `low` and `high` are provided, the range is `[low, high)`.
  * `size` is a tuple that defines the shape of the array.

<!-- end list -->

```python
# Generate a 2x3 array with random integers from 0 up to (but not including) 10
arr_int1 = np.random.randint(10, size=(2, 3))
print(f"Random integers in [0, 10):\n{arr_int1}\n")

# Generate a 2x3 array with random integers from 8 up to (but not including) 10
# The only possible values are 8 and 9
arr_int2 = np.random.randint(8, 10, size=(2, 3))
print(f"Random integers in [8, 10):\n{arr_int2}")
```

-----

## **3. `np.random.uniform()`**

This function is similar to `np.random.rand()`, but it allows you to specify a custom range `[low, high)` for your uniformly distributed random **floating-point numbers**.

**Syntax:** `np.random.uniform(low=0.0, high=1.0, size=None)`

```python
# Generate a 2x3 array with random floats from 0.0 up to (but not including) 10.0
arr_uni1 = np.random.uniform(10, size=(2, 3))
print(f"Random floats in [0, 10):\n{arr_uni1}\n")

# Generate a 2x3 array with random floats from 5.0 up to (but not including) 10.0
arr_uni2 = np.random.uniform(5, 10, size=(2, 3))
print(f"Random floats in [5, 10):\n{arr_uni2}")
```
___
# **`ndarray` Generation with Random Values 🎲**

মেশিন লার্নিং এবং ডেটা সায়েন্সে র‍্যান্ডম ডেটা তৈরি করা একটি মৌলিক কাজ। এটি সিন্থেটিক ডেটাসেট তৈরি করতে, মডেলের প্যারামিটার (যেমন একটি নিউরাল নেটওয়ার্কের ওয়েটস) ইনিশিয়ালাইজ করতে এবং র‍্যান্ডম স্যাম্পলিং-এর মাধ্যমে মডেলের পারফরম্যান্স মূল্যায়ন করতে ব্যবহৃত হয়। NumPy-এর `random` মডিউল এর জন্য একটি শক্তিশালী টুলকিট সরবরাহ করে।

-----

## **1. `np.random.rand()`**

এই ফাংশনটি একটি নির্দিষ্ট আকারের অ্যারে তৈরি করে এবং এটিকে **[0, 1)** ব্যবধানের মধ্যে একটি **ইউনিফর্ম ডিস্ট্রিবিউশন** থেকে র‍্যান্ডম স্যাম্পল দিয়ে পূর্ণ করে। এর মানে হলো ০ (অন্তর্ভুক্ত) এবং ১ (ব্যতীত) এর মধ্যে প্রতিটি সংখ্যা তৈরি হওয়ার সমান সম্ভাবনা থাকে।

**সিনট্যাক্স নোট:** অন্যান্য ফাংশনের মতো এখানে শেপ টুপল হিসেবে না দিয়ে, ডাইমেনশনগুলো আলাদা আর্গুমেন্ট হিসেবে পাস করতে হয়। যেমন: `np.random.rand(d0, d1, ...)`

```python
import numpy as np

# ৪টি র‍্যান্ডম ফ্লোট মানের একটি 1D অ্যারে তৈরি
arr_1d = np.random.rand(4)
print(f"1D Random Array:\n{arr_1d}\n")

# একটি 2D অ্যারে তৈরি (৪টি সারি, ৩টি কলাম)
arr_2d = np.random.rand(4, 3)
print(f"2D Random Array:\n{arr_2d}\n")

# একটি 3D অ্যারে তৈরি
arr_3d = np.random.rand(2, 4, 3)
print(f"3D Random Array:\n{arr_3d}")
```

`rand()` দিয়ে তৈরি অ্যারের `dtype` সবসময় `float64` হয়।

-----

## **2. `np.random.randint()`**

এই ফাংশনটি একটি নির্দিষ্ট আকারের অ্যারে তৈরি করে যা একটি নির্দিষ্ট পরিসরের র‍্যান্ডম **পূর্ণসংখ্যা (integers)** দিয়ে পূর্ণ থাকে।

**সিনট্যাক্স:** `np.random.randint(low, high=None, size=None)`

  * যদি শুধু `low` দেওয়া হয়, পরিসর হবে `[0, low)`।
  * যদি `low` এবং `high` উভয়ই দেওয়া হয়, পরিসর হবে `[low, high)`।
  * `size` একটি টুপল যা অ্যারের শেপ নির্ধারণ করে।

<!-- end list -->

```python
# ০ থেকে ১০-এর আগ পর্যন্ত (exclusive) র‍্যান্ডম ইন্টিজার দিয়ে একটি 2x3 অ্যারে তৈরি
arr_int1 = np.random.randint(10, size=(2, 3))
print(f"Random integers in [0, 10):\n{arr_int1}\n")

# ৮ থেকে ১০-এর আগ পর্যন্ত র‍্যান্ডম ইন্টিজার দিয়ে একটি 2x3 অ্যারে তৈরি
# এখানে শুধুমাত্র ৮ এবং ৯ মানগুলোই সম্ভব
arr_int2 = np.random.randint(8, 10, size=(2, 3))
print(f"Random integers in [8, 10):\n{arr_int2}")
```

-----

## **3. `np.random.uniform()`**

এই ফাংশনটি `np.random.rand()`-এর মতোই, কিন্তু এটি আপনাকে ইউনিফর্মলি ডিস্ট্রিবিউটেড র‍্যান্ডম **ফ্লোটিং-পয়েন্ট নম্বরগুলোর** জন্য একটি কাস্টম পরিসর `[low, high)` নির্দিষ্ট করতে দেয়।

**সিনট্যাক্স:** `np.random.uniform(low=0.0, high=1.0, size=None)`

```python
# ০.০ থেকে ১০.০-এর আগ পর্যন্ত র‍্যান্ডম ফ্লোট দিয়ে একটি 2x3 অ্যারে তৈরি
arr_uni1 = np.random.uniform(10, size=(2, 3))
print(f"Random floats in [0, 10):\n{arr_uni1}\n")

# ৫.০ থেকে ১০.০-এর আগ পর্যন্ত র‍্যান্ডম ফ্লোট দিয়ে একটি 2x3 অ্যারে তৈরি
arr_uni2 = np.random.uniform(5, 10, size=(2, 3))
print(f"Random floats in [5, 10):\n{arr_uni2}")
```

In [116]:
# np.random.rand()
# Create 1d array with random value
arr = np.random.rand(4)
print(arr)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

print()
# Create 2d array with random value
arr = np.random.rand(4,3)
print(arr)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print()

# Create 3d array with random value
arr = np.random.rand(2,4,3)
print(arr)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

#this value withing 0 to one range all are like equally distributed

[0.47145217 0.77241083 0.32241774 0.59199957]
float64
1
(4,)
float64

[[0.00329412 0.77721725 0.32284827]
 [0.60425329 0.58096305 0.03019702]
 [0.58732095 0.7322091  0.22667302]
 [0.43496581 0.05705622 0.79401279]]
float64
2
(4, 3)
float64

[[[0.27697981 0.84868112 0.99422411]
  [0.65170631 0.68871249 0.86337053]
  [0.29273968 0.29746853 0.47385468]
  [0.20260456 0.357075   0.17417866]]

 [[0.70980134 0.72491354 0.4653913 ]
  [0.5834332  0.64951802 0.42078038]
  [0.6456875  0.00371873 0.51257865]
  [0.36861186 0.91544508 0.53681805]]]
float64
3
(2, 4, 3)
float64


In [115]:
# Make int random array
# np.random.randint(range_with_comma, shape)
arr = np.random.randint(10, size=(2,3)) # Generate a 2x3 array with random integers from 0 up to (but not including) 10
print(arr)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

print()

# ro we can hardcode the start to end range
arr = np.random.randint(8,10, size=(2,3)) # Generate a 2x3 array with random integers from 8 up to (but not including) 10
# The only possible values are 8 and 9
print(arr)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

[[7 5 4]
 [9 8 9]]
int64
2
(2, 3)
int64

[[9 8 9]
 [8 8 8]]
int64
2
(2, 3)
int64


In [119]:
# np.random.uniform(range, shape): we can generate random floating value with in range

arr = np.random.uniform(10, size=(2,3)) # Generate a 2x3 array with random floats from 0.0 up to (but not including) 10.0
print(arr)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)


print()

arr = np.random.uniform(5,10, size=(2,3)) # Generate a 2x3 array with random floats from 5.0 up to (but not including) 10.0
print(arr)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)


[[5.01441972 9.60172903 7.8263776 ]
 [3.09363797 7.77904901 3.1625865 ]]
float64
2
(2, 3)
float64

[[6.09132681 7.56337183 8.31283609]
 [8.79001311 9.15119675 7.47461772]]
float64
2
(2, 3)
float64


# **`ndarray` Creation from a Range**

Instead of filling an array with a single value or random numbers, you can generate an array with a **sequence of numbers**. These functions are perfect for creating arrays with predictable, ordered data.

-----

## **1. `np.arange()`**

The `np.arange()` function is very similar to Python's built-in `range()` function but returns a NumPy array instead of a list iterator. It generates values within a half-open interval `[start, stop)`.

**Syntax:** `np.arange(start, stop, step)`

  * **`start`**: The starting value of the sequence (inclusive).
  * **`stop`**: The end value of the sequence (**exclusive**).
  * **`step`**: The difference between consecutive values.

<!-- end list -->

```python
import numpy as np

# Create a sequence of numbers from 1 to 10
arr = np.arange(1, 11, 1)
print(f"Array from arange: {arr}\n")

# We can easily reshape the output into a matrix
# Create a sequence from 1 to 9 and reshape it into a 3x3 matrix
matrix = np.arange(1, 10, 1).reshape(3, 3)
print(f"Reshaped matrix:\n{matrix}")
```

-----

## **2. `np.linspace()`**

The `np.linspace()` function (short for **lin**ear **space**) is incredibly useful. It creates an array with a specified number of evenly spaced points over a given interval.

**Key Difference:** Unlike `arange()`, `linspace()` **includes the `stop` value** in the array. You don't specify the step size; you specify how many total points you want, and NumPy calculates the step size for you.

**Syntax:** `np.linspace(start, stop, num)`

  * **`start`**: The starting value (inclusive).
  * **`stop`**: The ending value (**inclusive**).
  * **`num`**: The total number of points to generate.

<!-- end list -->

```python
# Generate 10 evenly spaced points from 1 to 10. The step is 1.0.
arr_10 = np.linspace(1, 10, 10)
print(f"10 points from 1 to 10:\n{arr_10}\n")

# Generate 19 evenly spaced points from 1 to 10. The step is calculated as 0.5.
arr_19 = np.linspace(1, 10, 19)
print(f"19 points from 1 to 10:\n{arr_19}")
```

-----

## **3. `np.logspace()`**

The `np.logspace()` function is the logarithmic equivalent of `linspace()`. It generates numbers that are evenly spaced on a **logarithmic scale**. This is very useful for plotting data that spans several orders of magnitude.

**How it works:** It creates a linear sequence of exponents (using `linspace`) and then raises a `base` to the power of those exponents.

  * **Default Base**: The default base is `10`.

**Syntax:** `np.logspace(start, stop, num, base=10.0)`

```python
# Generate 6 points from 10^0 to 10^5
# The exponents will be [0, 1, 2, 3, 4, 5]
arr_log = np.logspace(0, 5, 6)
print(f"Logspace with base 10:\n{arr_log}\n")

# You can also change the base
# Generate 6 points from 2^0 to 2^5
arr_log_base2 = np.logspace(0, 5, 6, base=2)
print(f"Logspace with base 2:\n{arr_log_base2}")
```

-----


## **`ndarray` Creation from a Range**

একটি অ্যারে শুধুমাত্র একটি নির্দিষ্ট মান বা র‍্যান্ডম সংখ্যা দিয়ে পূর্ণ না করে, আপনি **সংখ্যার ক্রম (sequence)** দিয়েও একটি অ্যারে তৈরি করতে পারেন। এই ফাংশনগুলো পূর্বাভাসযোগ্য, সাজানো ডেটা সহ অ্যারে তৈরির জন্য উপযুক্ত।

-----

## **১. `np.arange()`**

`np.arange()` ফাংশনটি পাইথনের বিল্ট-ইন `range()` ফাংশনের মতোই, কিন্তু এটি একটি লিস্ট ইটারেটরের পরিবর্তে একটি NumPy অ্যারে রিটার্ন করে। এটি একটি অর্ধ-খোলা ব্যবধান `[start, stop)`-এর মধ্যে মান তৈরি করে।

**সিনট্যাক্স:** `np.arange(start, stop, step)`

  * **`start`**: ক্রমের শুরুর মান (অন্তর্ভুক্ত)।
  * **`stop`**: ক্রমের শেষ মান (**ব্যতীত**)।
  * **`step`**: পরপর দুটি মানের মধ্যে পার্থক্য।

<!-- end list -->

```python
import numpy as np

# ১ থেকে ১০ পর্যন্ত সংখ্যার একটি ক্রম তৈরি
arr = np.arange(1, 11, 1)
print(f"arange থেকে তৈরি অ্যারে: {arr}\n")

# আমরা সহজেই আউটপুটটিকে একটি ম্যাট্রিক্সে রিশেপ করতে পারি
# ১ থেকে ৯ পর্যন্ত একটি ক্রম তৈরি করে সেটিকে 3x3 ম্যাট্রিক্সে রিশেপ করা হলো
matrix = np.arange(1, 10, 1).reshape(3, 3)
print(f"রিশেপ করা ম্যাট্রিক্স:\n{matrix}")
```

-----

## **২. `np.linspace()`**

`np.linspace()` ফাংশনটি (**lin**ear **space**-এর সংক্ষিপ্ত রূপ) অত্যন্ত দরকারী। এটি একটি নির্দিষ্ট ব্যবধানে, নির্দিষ্ট সংখ্যক সমদূরবর্তী পয়েন্টসহ একটি অ্যারে তৈরি করে।

**মূল পার্থক্য:** `arange()`-এর বিপরীতে, `linspace()` তার অ্যারেতে **`stop` মানটিকে অন্তর্ভুক্ত করে**। এখানে আপনি ধাপের আকার (step size) নির্দিষ্ট করেন না; বরং আপনি মোট কতগুলো পয়েন্ট চান তা নির্দিষ্ট করেন এবং NumPy আপনার জন্য ধাপের আকার গণনা করে নেয়।

**সিনট্যাক্স:** `np.linspace(start, stop, num)`

  * **`start`**: শুরুর মান (অন্তর্ভুক্ত)।
  * **`stop`**: শেষ মান (**অন্তর্ভুক্ত**)।
  * **`num`**: মোট কতগুলো পয়েন্ট তৈরি করতে হবে।

<!-- end list -->

```python
# ১ থেকে ১০ পর্যন্ত ১০টি সমদূরবর্তী পয়েন্ট তৈরি। এখানে ধাপ হলো ১.০।
arr_10 = np.linspace(1, 10, 10)
print(f"১ থেকে ১০ পর্যন্ত ১০টি পয়েন্ট:\n{arr_10}\n")

# ১ থেকে ১০ পর্যন্ত ১৯টি সমদূরবর্তী পয়েন্ট তৈরি। এখানে ধাপ গণনা করে ০.৫ পাওয়া গেছে।
arr_19 = np.linspace(1, 10, 19)
print(f"১ থেকে ১০ পর্যন্ত ১৯টি পয়েন্ট:\n{arr_19}")
```

-----

## **৩. `np.logspace()`**

`np.logspace()` ফাংশনটি `linspace()`-এর লগারিদমিক সমতুল্য। এটি এমন সংখ্যা তৈরি করে যা একটি **লগারিদমিক স্কেলে** সমদূরবর্তী। যে ডেটা কয়েক অর্ডারের ম্যাগনিচিউড জুড়ে বিস্তৃত থাকে, তা প্লট করার জন্য এটি খুব দরকারী।

**এটি কীভাবে কাজ করে:** এটি প্রথমে এক্সপোনেন্টগুলোর একটি রৈখিক ক্রম (`linspace` ব্যবহার করে) তৈরি করে এবং তারপরে একটি `base`-কে সেই এক্সপোনেন্টগুলোর ঘাতে (power) উন্নীত করে।

  * **ডিফল্ট বেস**: ডিফল্ট বেস হলো `10`।

**সিনট্যাক্স:** `np.logspace(start, stop, num, base=10.0)`

```python
# 10^0 থেকে 10^5 পর্যন্ত ৬টি পয়েন্ট তৈরি
# এক্সপোনেন্টগুলো হবে [0, 1, 2, 3, 4, 5]
arr_log = np.logspace(0, 5, 6)
print(f"বেস ১০ সহ Logspace:\n{arr_log}\n")

# আপনি বেস পরিবর্তনও করতে পারেন
# 2^0 থেকে 2^5 পর্যন্ত ৬টি পয়েন্ট তৈরি
arr_log_base2 = np.logspace(0, 5, 6, base=2)
print(f"বেস ২ সহ Logspace:\n{arr_log_base2}")
```

### **arange**

In [122]:
arr = np.arange(1,11,1)
print(arr)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
int64
1
(10,)
int64


### **reshape**

In [124]:
#Also we can make it 2d array matrix reshape function
arr = np.arange(1,10,1)
matrix = arr.reshape(3,3)
print(matrix)
print(matrix.dtype)
print(matrix.ndim)
print(matrix.shape)
print(matrix.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64
2
(3, 3)
int64


### **linspace**

In [126]:
arr = np.linspace(1,10,10)
print(arr)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
float64
1
(10,)
float64


In [127]:
arr = np.linspace(1,10,11)
print(arr)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]
float64
1
(11,)
float64


In [129]:
arr = np.linspace(1,10,19)
print(arr)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]
float64
1
(19,)
float64


### **logspace**


In [135]:
arr = np.logspace(0,5,6)
print(arr)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]


In [140]:
arr = np.linspace(0,5,10)
print(arr)

print()
arr = np.logspace(0,5,10) # here it doing 10^1, 10^0.55555556 ,  10^1.11111111 so on
print(arr)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


In [139]:
# we can also change base here
arr = np.logspace(0,5,6, base=2)
print(arr)

[ 1.  2.  4.  8. 16. 32.]


# **Creating Diagonal and Identity Matrices**

Diagonal and identity matrices are special types of square matrices that are fundamental building blocks in linear algebra and have significant applications in machine learning algorithms.

1.  **Diagonal Matrix**: A square matrix where all the elements are zero except for the elements on the **main diagonal** (where the row index equals the column index).
2.  **Identity Matrix**: A special type of diagonal matrix where all the elements on the main diagonal are **exactly 1**, and all other elements are 0.

-----

## **1. `np.diag()` - Creating a Diagonal Matrix**

The `np.diag()` function is versatile. When you pass it a 1D array-like object (list, tuple, or another NumPy array), it creates a 2D square matrix and places the elements of the input on the main diagonal.

```python
import numpy as np

# Create a diagonal matrix from a list
mat_diag_list = np.diag([1, 2, 3, 4])
print(f"Diagonal matrix from a list:\n{mat_diag_list}\n")
```

**Output:**

```
Diagonal matrix from a list:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
```

```python
# Create a diagonal matrix from a 1D NumPy array
mat_diag_arr = np.diag(np.arange(5, 8))
print(f"Diagonal matrix from a NumPy array:\n{mat_diag_arr}")
```

**Output:**

```
Diagonal matrix from a NumPy array:
[[5 0 0]
 [0 6 0]
 [0 0 7]]
```

*(Note: `np.diag()` can also be used to extract the diagonal elements from an existing matrix, making it a dual-purpose function.)*

-----

## **2. `np.eye()` - Creating an Identity Matrix**

The `np.eye()` function is the standard way to create an identity matrix. The name "eye" comes from the pronunciation of the letter "I", which is the mathematical symbol for an identity matrix.

```python
# Create a 3x3 identity matrix
mat_identity = np.eye(3)
print(f"3x3 Identity Matrix:\n{mat_identity}\n")
```

**Output:**

```
3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

The `eye()` function can also create non-square matrices and allows you to shift the diagonal of ones up or down using the optional `k` parameter.

  * `k=0` (default): Main diagonal.
  * `k > 0`: Shifts the diagonal upwards.
  * `k < 0`: Shifts the diagonal downwards.

<!-- end list -->

```python
# Create a 3x4 matrix with the main diagonal of ones
mat_rect = np.eye(3, 4)
print(f"3x4 matrix with k=0:\n{mat_rect}\n")

# Shift the diagonal up by 1 position (k=1)
mat_up = np.eye(3, 4, k=1)
print(f"3x4 matrix with k=1:\n{mat_up}\n")

# Shift the diagonal down by 1 position (k=-1)
mat_down = np.eye(3, 4, k=-1)
print(f"3x4 matrix with k=-1:\n{mat_down}")
```

**Output:**

```
3x4 matrix with k=0:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

3x4 matrix with k=1:
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

3x4 matrix with k=-1:
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
```

-----

## **Why are these matrices important in ML? 🤔**

### **Identity Matrix (I)**

Think of the identity matrix as the matrix equivalent of the number **1**. Just as `5 * 1 = 5`, multiplying any compatible matrix **A** by the identity matrix **I** results in **A** (`A * I = A`).

  * **Initialization**: In neural networks, weight matrices are sometimes initialized to be close to an identity matrix. This ensures that, at the start of training, the layer doesn't drastically change the input, providing a stable starting point.
  * **Regularization**: In techniques like **Ridge Regression**, a small multiple of the identity matrix (`λI`) is added to the data's covariance matrix. This helps to make the matrix invertible and prevents the model's parameters from becoming too large, which helps to reduce overfitting.

### **Diagonal Matrix (D)**

Diagonal matrices represent simple **scaling transformations**. When you multiply a vector by a diagonal matrix, each component of the vector is scaled by the corresponding diagonal element. This is a very efficient operation.

  * **Feature Scaling/Standardization**: Operations like standardizing features can be represented by diagonal matrices.
  * **Model Simplification**: In some probabilistic models like the **Gaussian Naive Bayes classifier**, the covariance matrix is assumed to be diagonal. This is a simplifying assumption that means the features are treated as statistically independent, which makes calculations much faster.
  * **Optimization Algorithms**: They appear frequently in the theory behind optimization algorithms and in matrix decomposition methods like **Singular Value Decomposition (SVD)**, where the matrix of singular values (**Σ**) is a diagonal matrix.


----
# **Creating Diagonal and Identity Matrices(Bangla)**

ডায়াগোনাল এবং আইডেন্টিটি ম্যাট্রিক্স হলো বিশেষ ধরনের বর্গ ম্যাট্রিক্স যা রৈখিক বীজগণিতের (linear algebra) মৌলিক অংশ এবং মেশিন লার্নিং অ্যালগরিদমে এদের উল্লেখযোগ্য প্রয়োগ রয়েছে।

1.  **ডায়াগোনাল ম্যাট্রিক্স (Diagonal Matrix)**: একটি বর্গ ম্যাট্রিক্স যেখানে **প্রধান কর্ণ** (main diagonal) বরাবর উপাদানগুলো ছাড়া বাকি সব উপাদান শূন্য থাকে (যেখানে সারি এবং কলামের ইনডেক্স সমান)।
2.  **আইডেন্টিটি ম্যাট্রিক্স (Identity Matrix)**: এটি একটি বিশেষ ধরনের ডায়াগোনাল ম্যাট্রিক্স যেখানে প্রধান কর্ণের সমস্ত উপাদান **ঠিক ১** থাকে এবং বাকি সব উপাদান শূন্য থাকে।

-----

## **1. `np.diag()` - ডায়াগোনাল ম্যাট্রিক্স তৈরি**

`np.diag()` ফাংশনটি বেশ বহুমুখী। যখন আপনি এটিকে একটি 1D অ্যারের মতো অবজেক্ট (লিস্ট, টুপল, বা অন্য NumPy অ্যারে) পাস করেন, তখন এটি একটি 2D বর্গ ম্যাট্রিক্স তৈরি করে এবং ইনপুটের উপাদানগুলোকে প্রধান কর্ণে স্থাপন করে।

```python
import numpy as np

# একটি লিস্ট থেকে ডায়াগোনাল ম্যাট্রিক্স তৈরি
mat_diag_list = np.diag([1, 2, 3, 4])
print(f"লিস্ট থেকে ডায়াগোনাল ম্যাট্রিক্স:\n{mat_diag_list}\n")
```

**আউটপুট:**

```
লিস্ট থেকে ডায়াগোনাল ম্যাট্রিক্স:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
```

```python
# একটি NumPy অ্যারে থেকে ডায়াগোনাল ম্যাট্রিক্স তৈরি
mat_diag_arr = np.diag(np.arange(5, 8))
print(f"NumPy অ্যারে থেকে ডায়াগোনাল ম্যাট্রিক্স:\n{mat_diag_arr}")
```

**আউটপুট:**

```
NumPy অ্যারে থেকে ডায়াগোনাল ম্যাট্রিক্স:
[[5 0 0]
 [0 6 0]
 [0 0 7]]
```

*(দ্রষ্টব্য: `np.diag()` একটি বিদ্যমান ম্যাট্রিক্স থেকে কর্ণের উপাদানগুলো বের করার জন্যও ব্যবহার করা যেতে পারে, যা এটিকে একটি দ্বৈত-উদ্দেশ্যমূলক ফাংশন করে তোলে।)*

-----

## **2. `np.eye()` - আইডেন্টিটি ম্যাট্রিক্স তৈরি**

আইডেন্টিটি ম্যাট্রিক্স তৈরি করার জন্য `np.eye()` একটি স্ট্যান্ডার্ড ফাংশন। এর নাম "eye" এসেছে "I" অক্ষরের উচ্চারণ থেকে, যা আইডেন্টিটি ম্যাট্রিক্সের গাণিতিক প্রতীক।

```python
# একটি 3x3 আইডেন্টিটি ম্যাট্রিক্স তৈরি
mat_identity = np.eye(3)
print(f"3x3 আইডেন্টিটি ম্যাট্রিক্স:\n{mat_identity}\n")
```

**আউটপুট:**

```
3x3 আইডেন্টিটি ম্যাট্রিক্স:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

`eye()` ফাংশনটি বর্গাকার নয় এমন ম্যাট্রিক্সও তৈরি করতে পারে এবং `k` প্যারামিটার ব্যবহার করে আপনি ১-এর কর্ণটিকে উপরে বা নিচে সরাতে পারেন।

  * `k=0` (ডিফল্ট): প্রধান কর্ণ।
  * `k > 0`: কর্ণটিকে উপরে সরায়।
  * `k < 0`: কর্ণটিকে নিচে সরায়।

<!-- end list -->

```python
# ১-এর প্রধান কর্ণ সহ একটি 3x4 ম্যাট্রিক্স
mat_rect = np.eye(3, 4)
print(f"k=0 সহ 3x4 ম্যাট্রিক্স:\n{mat_rect}\n")

# কর্ণটিকে ১ ঘর উপরে সরানো হলো (k=1)
mat_up = np.eye(3, 4, k=1)
print(f"k=1 সহ 3x4 ম্যাট্রিক্স:\n{mat_up}\n")

# কর্ণটিকে ১ ঘর নিচে সরানো হলো (k=-1)
mat_down = np.eye(3, 4, k=-1)
print(f"k=-1 সহ 3x4 ম্যাট্রিক্স:\n{mat_down}")
```

**আউটপুট:**

```
k=0 সহ 3x4 ম্যাট্রিক্স:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

k=1 সহ 3x4 ম্যাট্রিক্স:
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

k=-1 সহ 3x4 ম্যাট্রিক্স:
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
```

-----

## **মেশিন লার্নিং-এ এই ম্যাট্রিক্সগুলো কেন গুরুত্বপূর্ণ? 🤔**

### **আইডেন্টিটি ম্যাট্রিক্স (I)**

আইডেন্টিটি ম্যাট্রিক্সকে সংখ্যা **১**-এর ম্যাট্রিক্স সমতুল্য হিসেবে ভাবুন। যেমন `5 * 1 = 5` হয়, তেমনই যেকোনো সামঞ্জস্যপূর্ণ ম্যাট্রিক্স **A**-কে আইডেন্টিটি ম্যাট্রিক্স **I** দ্বারা গুণ করলে **A** পাওয়া যায় (`A * I = A`)।

  * **ইনিশিয়ালাইজেশন (Initialization)**: নিউরাল নেটওয়ার্কে, ওয়েট ম্যাট্রিক্সগুলোকে কখনও কখনও আইডেন্টিটি ম্যাট্রিক্সের কাছাকাছি মানে ইনিশিয়ালাইজ করা হয়। এটি নিশ্চিত করে যে, প্রশিক্ষণের শুরুতে লেয়ারটি ইনপুটকে খুব বেশি পরিবর্তন করবে না, যা একটি স্থিতিশীল সূচনা প্রদান করে।
  * **রেগুলারাইজেশন (Regularization)**: **রিজ রিগ্রেশন (Ridge Regression)**-এর মতো কৌশলে, ডেটার কোভ্যারিয়েন্স ম্যাট্রিক্সের সাথে আইডেন্টিটি ম্যাট্রিক্সের একটি ছোট গুণিতক (`λI`) যোগ করা হয়। এটি ম্যাট্রিক্সটিকে ইনভার্টেবল করতে সাহায্য করে এবং মডেলের প্যারামিটারগুলোকে খুব বড় হতে বাধা দেয়, যা ওভারফিটিং কমাতে সাহায্য করে।

### **ডায়াগোনাল ম্যাট্রিক্স (D)**

ডায়াগোনাল ম্যাট্রিক্স সাধারণ **স্কেলিং রূপান্তর (scaling transformations)** প্রকাশ করে। যখন আপনি একটি ভেক্টরকে একটি ডায়াগোনাল ম্যাট্রিক্স দ্বারা গুণ করেন, তখন ভেক্টরের প্রতিটি উপাদান সংশ্লিষ্ট ডায়াগোনাল উপাদান দ্বারা স্কেল বা গুণ হয়। এটি একটি অত্যন্ত কার্যকর অপারেশন।

  * **ফিচার স্কেলিং/স্ট্যান্ডার্ডাইজেশন**: ফিচার স্ট্যান্ডার্ডাইজ করার মতো অপারেশনগুলোকে ডায়াগোনাল ম্যাট্রিক্স দ্বারা প্রকাশ করা যেতে পারে।
  * **মডেল সরলীকরণ**: কিছু সম্ভাব্যতা মডেলে, যেমন **গাউসিয়ান নাইভ বেইজ ক্লাসিফায়ার (Gaussian Naive Bayes classifier)**, কোভ্যারিয়েন্স ম্যাট্রিক্সকে ডায়াগোনাল বলে ধরে নেওয়া হয়। এই সরল অনুমানের অর্থ হলো ফিচারগুলোকে পরিসংখ্যানগতভাবে স্বাধীন হিসেবে গণ্য করা হয়, যা গণনাকে অনেক দ্রুত করে তোলে।
  * **অপ্টিমাইজেশন অ্যালগরিদম**: অপ্টিমাইজেশন অ্যালগরিদমের তত্ত্ব এবং **সিঙ্গুলার ভ্যালু ডিকম্পোজিশন (SVD)**-এর মতো ম্যাট্রিক্স ডিকম্পোজিশন পদ্ধতিতে এগুলো প্রায়শই দেখা যায়, যেখানে সিঙ্গুলার মানের ম্যাট্রিক্সটি (**Σ**) একটি ডায়াগোনাল ম্যাট্রিক্স।

### **diag()**

In [141]:
mat = np.diag([1,2,3,4])
print(mat)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [153]:
# It can hold tuple or can be ndarray
mat = np.diag(np.arange(1,7))
print(mat)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


### **eye()**

In [145]:
# identitiy Matrix

mat = np.eye(3)
print(mat)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [146]:
# we can also make identity matrix but it it is not identify matrix when it is not squar
mat = np.eye(3,4)
print(mat)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [149]:
# We can move diagnal bottom to using -1 and top to +1
mat = np.eye(3,4,-1)
print(mat)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [150]:
mat = np.eye(3,4,1)
print(mat)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# **`ndarray` Indexing and Slicing**

Accessing and manipulating specific parts of an array is a fundamental operation. NumPy provides a powerful and flexible syntax for indexing (accessing single elements) and slicing (accessing sub-arrays) that is similar to Python lists but extended for multiple dimensions.

-----

## **1. Working with 1D Arrays**

Indexing and slicing on 1D arrays work just like they do for Python lists.

```python
import numpy as np

arr = np.arange(1, 10)
print(f"Original 1D array:\n{arr}\n")
```

**Output:**

```
Original 1D array:
[1 2 3 4 5 6 7 8 9]
```

### **Accessing and Modifying Elements**

You use square brackets `[]` with the index of the element you want to access. Remember, indexing starts at 0.

```python
# Access the element at index 2 (the third element)
print(f"Element at index 2: {arr[2]}\n")

# Change the value at index 2
arr[2] = 100
print(f"Array after modification:\n{arr}\n")
```

**Output:**

```
Element at index 2: 3

Array after modification:
[  1   2 100   4   5   6   7   8   9]
```

### **Slicing 1D Arrays**

The slicing syntax is `[start:stop:step]`.

```python
# Slice from index 2 up to (but not including) index 9, with a step of 2
sliced_arr = arr[2:9:2]
print(f"Sliced array [2:9:2]:\n{sliced_arr}")
```

**Output:**

```
Sliced array [2:9:2]:
[100   5   7   9]
```

-----

## **2. Working with 2D Arrays (Matrices)**

For 2D arrays, indexing and slicing are extended with a comma-separated syntax: `[row_specifier, column_specifier]`.

```python
arr2 = np.arange(1, 10).reshape(3, 3)
print(f"Original 2D array:\n{arr2}\n")
```

**Output:**

```
Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```

### **Accessing and Modifying Elements**

You can use `[row][col]` syntax, but the more efficient and standard NumPy way is `[row, col]`.

```python
# Access the element in the first row (index 0) and second column (index 1)
element = arr2[0, 1] # Preferred NumPy syntax
print(f"Element at [0, 1]: {element}\n")

# Reassign the value at that position
arr2[0, 1] = 20
print(f"Array after modification:\n{arr2}\n")
```

**Output:**

```
Element at [0, 1]: 2

Array after modification:
[[ 1 20  3]
 [ 4  5  6]
 [ 7  8  9]]
```

### **Slicing 2D Arrays**

The syntax is `[row_start:row_end:row_step, col_start:col_end:col_step]`. A colon `:` by itself means "select all".

```python
# Let's reset the array for clarity
arr2 = np.arange(1, 10).reshape(3, 3)
print(f"Reset 2D array:\n{arr2}\n")

# Getting one or more rows
print(f"Getting the second row (index 1):\n{arr2[1, :]}\n") # or simply arr2[1]
print(f"Getting first and third rows (step=2):\n{arr2[0:3:2, :]}\n")


# Getting one or more columns
print(f"Getting the first column (index 0):\n{arr2[:, 0:1]}\n")
print(f"Getting first and third columns (step=2):\n{arr2[:, 0:3:2]}\n")


# Getting a portion (submatrix)
# Get the top-left 2x2 matrix
# Rows 0 to 2 (exclusive), Columns 0 to 2 (exclusive)
submatrix = arr2[0:2, 0:2]
print(f"Top-left 2x2 submatrix:\n{submatrix}")
```

**Output:**

```
Reset 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Getting the second row (index 1):
[4 5 6]

Getting first and third rows (step=2):
[[1 2 3]
 [7 8 9]]

Getting the first column (index 0):
[[1]
 [4]
 [7]]

Getting first and third columns (step=2):
[[1 3]
 [4 6]
 [7 9]]

Top-left 2x2 submatrix:
[[1 2]
 [4 5]]
```
---

## **`ndarray` ইনডেক্সিং এবং স্লাইসিং**

একটি অ্যারের নির্দিষ্ট অংশ অ্যাক্সেস এবং পরিবর্তন করা একটি মৌলিক কাজ। NumPy **ইনডেক্সিং** (একক উপাদান অ্যাক্সেস করা) এবং **স্লাইসিং** (সাব-অ্যারে অ্যাক্সেস করা)-এর জন্য একটি শক্তিশালী এবং নমনীয় সিনট্যাক্স সরবরাহ করে, যা পাইথন লিস্টের মতোই কিন্তু একাধিক ডাইমেনশনের জন্য প্রসারিত।

-----

## **১. 1D অ্যারের সাথে কাজ করা**

1D অ্যারেতে ইনডেক্সিং এবং স্লাইসিং পাইথন লিস্টের মতোই কাজ করে।

```python
import numpy as np

arr = np.arange(1, 10)
print(f"মূল 1D অ্যারে:\n{arr}\n")
```

**আউটপুট:**

```
মূল 1D অ্যারে:
[1 2 3 4 5 6 7 8 9]
```

### **উপাদান অ্যাক্সেস এবং পরিবর্তন করা**

আপনি যে উপাদানটি অ্যাক্সেস করতে চান তার ইনডেক্স সহ স্কয়ার ব্র্যাকেট `[]` ব্যবহার করবেন। মনে রাখবেন, ইনডেক্সিং ০ থেকে শুরু হয়।

```python
# ইনডেক্স ২-এর উপাদানটি (তৃতীয় উপাদান) অ্যাক্সেস করা
print(f"ইনডেক্স ২-এর উপাদান: {arr[2]}\n")

# ইনডেক্স ২-এর মান পরিবর্তন করা
arr[2] = 100
print(f"পরিবর্তনের পর অ্যারে:\n{arr}\n")
```

**আউটপুট:**

```
ইনডেক্স ২-এর উপাদান: 3

পরিবর্তনের পর অ্যারে:
[  1   2 100   4   5   6   7   8   9]
```

### **1D অ্যারে স্লাইস করা**

স্লাইসিং-এর সিনট্যাক্স হলো `[start:stop:step]`।

```python
# ইনডেক্স ২ থেকে ৯-এর আগ পর্যন্ত (exclusive) স্লাইস করা, যেখানে ধাপ ২
sliced_arr = arr[2:9:2]
print(f"স্লাইস করা অ্যারে [2:9:2]:\n{sliced_arr}")
```

**আউটপুট:**

```
স্লাইস করা অ্যারে [2:9:2]:
[100   5   7   9]
```

-----

## **২. 2D অ্যারের (ম্যাট্রিক্স) সাথে কাজ করা**

2D অ্যারের জন্য, ইনডেক্সিং এবং স্লাইসিং কমা-দ্বারা পৃথক করা সিনট্যাক্স ব্যবহার করে প্রসারিত করা হয়েছে: `[row_specifier, column_specifier]`।

```python
arr2 = np.arange(1, 10).reshape(3, 3)
print(f"মূল 2D অ্যারে:\n{arr2}\n")
```

**আউটপুট:**

```
মূল 2D অ্যারে:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```

### **উপাদান অ্যাক্সেস এবং পরিবর্তন করা**

আপনি `[row][col]` সিনট্যাক্স ব্যবহার করতে পারেন, তবে NumPy-এর জন্য বেশি কার্যকর এবং স্ট্যান্ডার্ড উপায় হলো `[row, col]`।

```python
# প্রথম সারি (ইনডেক্স ০) এবং দ্বিতীয় কলামের (ইনডেক্স ১) উপাদান অ্যাক্সেস করা
element = arr2[0, 1] # NumPy-এর পছন্দের সিনট্যাক্স
print(f"[0, 1] অবস্থানের উপাদান: {element}\n")

# সেই অবস্থানের মান পরিবর্তন করা
arr2[0, 1] = 20
print(f"পরিবর্তনের পর অ্যারে:\n{arr2}\n")
```

**আউটপুট:**

```
[0, 1] অবস্থানের উপাদান: 2

পরিবর্তনের পর অ্যারে:
[[ 1 20  3]
 [ 4  5  6]
 [ 7  8  9]]
```

### **2D অ্যারে স্লাইস করা**

সিনট্যাক্সটি হলো `[row_start:row_end:row_step, col_start:col_end:col_step]`। একটি কোলন `:` একা থাকলে তার মানে হলো "সবগুলো নির্বাচন করো"।

```python
# স্বচ্ছতার জন্য অ্যারেটি রিসেট করা হলো
arr2 = np.arange(1, 10).reshape(3, 3)
print(f"রিসেট করা 2D অ্যারে:\n{arr2}\n")

# এক বা একাধিক সারি পাওয়া
print(f"দ্বিতীয় সারি (ইনডেক্স ১) পাওয়া:\n{arr2[1, :]}\n") # অথবা শুধু arr2[1]
print(f"প্রথম এবং তৃতীয় সারি পাওয়া (ধাপ=২):\n{arr2[0:3:2, :]}\n")


# এক বা একাধিক কলাম পাওয়া
print(f"প্রথম কলাম (ইনডেক্স ০) পাওয়া:\n{arr2[:, 0:1]}\n")
print(f"প্রথম এবং তৃতীয় কলাম পাওয়া (ধাপ=২):\n{arr2[:, 0:3:2]}\n")


# একটি অংশ (সাবম্যাট্রিক্স) পাওয়া
# উপরের-বামের 2x2 ম্যাট্রিক্সটি পাওয়া
# সারি ০ থেকে ২ (exclusive), কলাম ০ থেকে ২ (exclusive)
submatrix = arr2[0:2, 0:2]
print(f"উপরের-বামের 2x2 সাবম্যাট্রিক্স:\n{submatrix}")
```

**আউটপুট:**

```
রিসেট করা 2D অ্যারে:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

দ্বিতীয় সারি (ইনডেক্স ১) পাওয়া:
[4 5 6]

প্রথম এবং তৃতীয় সারি পাওয়া (ধাপ=২):
[[1 2 3]
 [7 8 9]]

প্রথম কলাম (ইনডেক্স ০) পাওয়া:
[[1]
 [4]
 [7]]

প্রথম এবং তৃতীয় কলাম পাওয়া (ধাপ=২):
[[1 3]
 [4 6]
 [7 9]]

উপরের-বামের 2x2 সাবম্যাট্রিক্স:
[[1 2]
 [4 5]]
```

In [165]:
# work with 1d array
arr = np.arange(1,10)
print(arr)

# access index
print(arr[2])

# change the value of index
arr[2] = 100
print(arr)


# slicing array
print(arr[2:9:2])

[1 2 3 4 5 6 7 8 9]
3
[  1   2 100   4   5   6   7   8   9]
[100   5   7   9]


In [169]:
# working with 2d array
arr2 = np.reshape(np.arange(1,10),(3,3))
print(arr2)

# Accesing element
print(arr2[0][1])

# reassing value
arr2[0][1] = 20
print(arr2[0][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
20


In [171]:
# Slicing 2d array
# how it work [row_start : row_end : row_step , col_start : col_end : col_step]

# Getting a row
# working with 2d array
arr2 = np.reshape(np.arange(1,10),(3,3))
print(arr2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]


In [183]:
# Gettig a row
print(arr2[1:2,])

# Getting one or more row with step
print(arr2[0:3:2,])


[[4 5 6]]
[[1 2 3]
 [7 8 9]]


In [186]:
# getting a column
print(arr2[::,0:1])

# Getting one or more row with step
print(arr2[::,0:3:2])


[[1]
 [4]
 [7]]
[[1 3]
 [4 6]
 [7 9]]


In [188]:
# Getting a protion
print(arr2[0:2, 0:2])

[[1 2]
 [4 5]]


# **`ndarray`: Views, Copies, Advanced Indexing, and Iteration**

This note covers some advanced but crucial concepts: how NumPy handles memory when slicing, how to select elements in non-sequential ways, and the best practices for iterating over arrays.

-----

## **1. Slicing: View vs. Copy 🔗**

This is one of the most important concepts to understand in NumPy for avoiding unexpected bugs. By default, slicing a NumPy array creates a **view**, not a copy.

A **view** is a new array object that looks at the *same underlying data* as the original array. This makes slicing very fast and memory-efficient. However, it means that if you modify the view, you also modify the original array.

```python
import numpy as np

arr = np.linspace(1, 10, 10, dtype=int)
print(f"Original array:\n{arr}\n")

# Slicing creates a view
mod_arr_view = arr[1:5]
print(f"This is a view of the original:\n{mod_arr_view}\n")

# Modify the first element of the view
mod_arr_view[0] = 200
print(f"The view is modified:\n{mod_arr_view}\n")

# The original array is also changed!
print(f"The original array has also been changed:\n{arr}\n")
```

**Output:**

```
Original array:
[ 1  2  3  4  5  6  7  8  9 10]

This is a view of the original:
[2 3 4 5]

The view is modified:
[200   3   4   5]

The original array has also been changed:
[  1 200   3   4   5   6   7   8   9  10]
```

### **Making an Explicit Copy**

If you want to modify a slice without affecting the original array, you must create an explicit **copy** using the `.copy()` method.

```python
arr = np.linspace(1, 10, 10, dtype=int)
print(f"Original array:\n{arr}\n")

# Create an explicit copy
mod_arr_copy = arr[0:4].copy()
mod_arr_copy[1] = 200 # Modify the copy

print(f"The modified copy is:\n{mod_arr_copy}\n")
print(f"The original array is NOT changed:\n{arr}")
```

**Output:**

```
Original array:
[ 1  2  3  4  5  6  7  8  9 10]

The modified copy is:
[  1 200   3   4]

The original array is NOT changed:
[ 1  2  3  4  5  6  7  8  9 10]
```

-----

## **2. Advanced Indexing**

Standard slicing is limited to creating sequential views. Advanced indexing (also known as "fancy indexing") allows you to select any arbitrary set of elements.

### **Integer Array Indexing**

You can pass a list or an array of indices to access multiple, specific elements at once.

```python
arr = np.linspace(1, 10, 10, dtype=int)
print(f"Original array:\n{arr}\n")

# Access elements at indices 0, 1, 3, 4, and 5
values = arr[[0, 1, 3, 4, 5]]
print(f"Specifically chosen values:\n{values}\n")

# For 2D arrays, you pass a tuple of lists: ([rows], [cols])
arr2 = np.arange(1, 10).reshape(3, 3)
print(f"Original 2D array:\n{arr2}\n")

# Get the elements at (row 1, col 1) and (row 1, col 2)
elements = arr2[[1, 1], [1, 2]]
print(f"Elements at (1,1) and (1,2):\n{elements}")
```

**Output:**

```
Original array:
[ 1  2  3  4  5  6  7  8  9 10]

Specifically chosen values:
[1 2 4 5 6]

Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Elements at (1,1) and (1,2):
[5 6]
```

### **Boolean Indexing (Filtering)**

You can use a boolean expression to select or modify elements that meet a certain condition.

```python
arr = np.arange(1, 10).reshape(3, 3)
print(f"Original array:\n{arr}\n")

# Select all elements greater than 2
filtered_arr = arr[arr > 2]
print(f"Values greater than 2:\n{filtered_arr}\n")

# Reassign a value to all elements greater than 8
arr[arr > 8] = 0
print(f"Array after reassigning values > 8 to 0:\n{arr}")
```

**Output:**

```
Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Values greater than 2:
[3 4 5 6 7 8 9]

Array after reassigning values > 8 to 0:
[[1 2 3]
 [4 5 6]
 [7 8 0]]
```

-----

## **3. Iterating Over Arrays 🚶‍♂️**

While vectorized operations are always preferred for speed, sometimes you need to loop through an array.

```python
arr = np.arange(1, 10).reshape(3, 3)

# Standard Python loop iterates over rows
print("Iterating over rows:")
for row in arr:
  print(row)

# Nested loop to access each item
print("\nIterating over each element (nested loop):")
for row in arr:
  for col in row:
    print(col, end=" ")
```

**Output:**

```
Iterating over rows:
[1 2 3]
[4 5 6]
[7 8 9]

Iterating over each element (nested loop):
1 2 3 4 5 6 7 8 9
```

### **The NumPy Way: `np.nditer()`**

For large or multi-dimensional arrays, the `np.nditer()` iterator is much more efficient. It provides a clean way to visit every element regardless of the array's shape.

```python
arr = np.arange(1, 10).reshape(3, 3)
print("\n\nIterating with np.nditer():")
for i in np.nditer(arr):
  print(i, end=" ")
```

**Output:**

```
Iterating with np.nditer():
1 2 3 4 5 6 7 8 9
```

___

## **`ndarray`: ভিউ, কপি, অ্যাডভান্সড ইনডেক্সিং এবং ইটারেশন**

এই নোটে কিছু অ্যাডভান্সড কিন্তু অত্যন্ত গুরুত্বপূর্ণ বিষয় আলোচনা করা হয়েছে: স্লাইস করার সময় NumPy কীভাবে মেমরি পরিচালনা করে, নন-সিকোয়েন্সিয়াল পদ্ধতিতে কীভাবে উপাদান নির্বাচন করতে হয় এবং অ্যারের উপর ইটারেট করার সেরা উপায়গুলো কী কী।

-----

## **১. স্লাইসিং: ভিউ বনাম কপি 🔗**

অপ্রত্যাশিত বাগ এড়ানোর জন্য NumPy-তে এটি একটি সবচেয়ে গুরুত্বপূর্ণ ধারণা। ডিফল্টভাবে, একটি NumPy অ্যারে স্লাইস করলে একটি **ভিউ (view)** তৈরি হয়, কপি নয়।

একটি **ভিউ** হলো একটি নতুন অ্যারে অবজেক্ট যা মূল অ্যারের *একই ডেটার দিকে নির্দেশ করে*। এটি স্লাইসিংকে খুব দ্রুত এবং মেমরি-সাশ্রয়ী করে তোলে। তবে, এর মানে হলো আপনি যদি ভিউটি পরিবর্তন করেন, তবে মূল অ্যারেটিও পরিবর্তিত হয়ে যাবে।

```python
import numpy as np

arr = np.linspace(1, 10, 10, dtype=int)
print(f"মূল অ্যারে:\n{arr}\n")

# স্লাইসিং একটি ভিউ তৈরি করে
mod_arr_view = arr[1:5]
print(f"এটি মূল অ্যারের একটি ভিউ:\n{mod_arr_view}\n")

# ভিউয়ের প্রথম উপাদানটি পরিবর্তন করা হলো
mod_arr_view[0] = 200
print(f"ভিউটি পরিবর্তিত হয়েছে:\n{mod_arr_view}\n")

# মূল অ্যারেটিও পরিবর্তিত হয়ে গেছে!
print(f"মূল অ্যারেটিও পরিবর্তিত হয়েছে:\n{arr}\n")
```

**আউটপুট:**

```
মূল অ্যারে:
[ 1  2  3  4  5  6  7  8  9 10]

এটি মূল অ্যারের একটি ভিউ:
[2 3 4 5]

ভিউটি পরিবর্তিত হয়েছে:
[200   3   4   5]

মূল অ্যারেটিও পরিবর্তিত হয়েছে:
[  1 200   3   4   5   6   7   8   9  10]
```

### **একটি সুস্পষ্ট কপি তৈরি করা**

আপনি যদি মূল অ্যারেটিকে প্রভাবিত না করে একটি স্লাইস পরিবর্তন করতে চান, তবে আপনাকে অবশ্যই `.copy()` মেথড ব্যবহার করে একটি সুস্পষ্ট **কপি** তৈরি করতে হবে।

```python
arr = np.linspace(1, 10, 10, dtype=int)
print(f"মূল অ্যারে:\n{arr}\n")

# একটি সুস্পষ্ট কপি তৈরি
mod_arr_copy = arr[0:4].copy()
mod_arr_copy[1] = 200 # কপিটি পরিবর্তন করা হলো

print(f"পরিবর্তিত কপিটি হলো:\n{mod_arr_copy}\n")
print(f"মূল অ্যারেটি পরিবর্তিত হয়নি:\n{arr}")
```

**আউটপুট:**

```
মূল অ্যারে:
[ 1  2  3  4  5  6  7  8  9 10]

পরিবর্তিত কপিটি হলো:
[  1 200   3   4]

মূল অ্যারেটি পরিবর্তিত হয়নি:
[ 1  2  3  4  5  6  7  8  9 10]
```

-----

## **২. অ্যাডভান্সড ইনডেক্সিং**

স্ট্যান্ডার্ড স্লাইসিং শুধুমাত্র ক্রমিক (sequential) ভিউ তৈরি করার মধ্যে সীমাবদ্ধ। অ্যাডভান্সড ইনডেক্সিং (যাকে "ফ্যান্সি ইনডেক্সিং"ও বলা হয়) আপনাকে যেকোনো ইচ্ছামত উপাদান নির্বাচন করার অনুমতি দেয়।

### **ইন্টিজার অ্যারে ইনডেক্সিং**

আপনি একাধিক, নির্দিষ্ট উপাদান একসাথে অ্যাক্সেস করার জন্য ইনডেক্সগুলোর একটি লিস্ট বা অ্যারে পাস করতে পারেন।

```python
arr = np.linspace(1, 10, 10, dtype=int)
print(f"মূল অ্যারে:\n{arr}\n")

# ইনডেক্স ০, ১, ৩, ৪, এবং ৫ এর উপাদানগুলো অ্যাক্সেস করা
values = arr[[0, 1, 3, 4, 5]]
print(f"নির্দিষ্টভাবে নির্বাচিত মান:\n{values}\n")

# 2D অ্যারের জন্য, আপনি লিস্টের একটি টুপল পাস করবেন: ([সারি], [কলাম])
arr2 = np.arange(1, 10).reshape(3, 3)
print(f"মূল 2D অ্যারে:\n{arr2}\n")

# (সারি ১, কলাম ১) এবং (সারি ১, কলাম ২) এর উপাদানগুলো পাওয়া
elements = arr2[[1, 1], [1, 2]]
print(f"(1,1) এবং (1,2) অবস্থানের উপাদান:\n{elements}")
```

**আউটপুট:**

```
মূল অ্যারে:
[ 1  2  3  4  5  6  7  8  9 10]

নির্দিষ্টভাবে নির্বাচিত মান:
[1 2 4 5 6]

মূল 2D অ্যারে:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

(1,1) এবং (1,2) অবস্থানের উপাদান:
[5 6]
```

### **বুলিয়ান ইনডেক্সিং (ফিল্টারিং)**

আপনি একটি নির্দিষ্ট শর্ত পূরণকারী উপাদানগুলো নির্বাচন বা পরিবর্তন করতে একটি বুলিয়ান এক্সপ্রেশন ব্যবহার করতে পারেন।

```python
arr = np.arange(1, 10).reshape(3, 3)
print(f"মূল অ্যারে:\n{arr}\n")

# ২-এর চেয়ে বড় সমস্ত উপাদান নির্বাচন করা
filtered_arr = arr[arr > 2]
print(f"২-এর চেয়ে বড় মানগুলো:\n{filtered_arr}\n")

# ৮-এর চেয়ে বড় সমস্ত উপাদানের মান পরিবর্তন করা
arr[arr > 8] = 0
print(f"৮-এর চেয়ে বড় মানগুলোকে ০ করার পর অ্যারে:\n{arr}")
```

**আউটপুট:**

```
মূল অ্যারে:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

২-এর চেয়ে বড় মানগুলো:
[3 4 5 6 7 8 9]

৮-এর চেয়ে বড় মানগুলোকে ০ করার পর অ্যারে:
[[1 2 3]
 [4 5 6]
 [7 8 0]]
```

-----

## **৩. অ্যারের উপর ইটারেট করা 🚶‍♂️**

যদিও গতির জন্য ভেক্টরাইজড অপারেশন সবসময়ই শ্রেয়, কখনও কখনও আপনাকে একটি অ্যারের মধ্য দিয়ে লুপ করতে হতে পারে।

```python
arr = np.arange(1, 10).reshape(3, 3)

# সাধারণ পাইথন লুপ সারিগুলোর উপর ইটারেট করে
print("সারিগুলোর উপর ইটারেট করা:")
for row in arr:
  print(row)

# প্রতিটি আইটেম অ্যাক্সেস করার জন্য নেস্টেড লুপ
print("\nপ্রতিটি উপাদানের উপর ইটারেট করা (নেস্টেড লুপ):")
for row in arr:
  for col in row:
    print(col, end=" ")
```

**আউটপুট:**

```
সারিগুলোর উপর ইটারেট করা:
[1 2 3]
[4 5 6]
[7 8 9]

প্রতিটি উপাদানের উপর ইটারেট করা (নেস্টেড লুপ):
1 2 3 4 5 6 7 8 9
```

### **NumPy-এর উপায়: `np.nditer()`**

বড় বা বহুমাত্রিক অ্যারের জন্য `np.nditer()` ইটারেটরটি অনেক বেশি কার্যকর। এটি অ্যারের শেপ নির্বিশেষে প্রতিটি উপাদান ভিজিট করার একটি সহজ উপায় সরবরাহ করে।

```python
arr = np.arange(1, 10).reshape(3, 3)
print("\n\nnp.nditer() দিয়ে ইটারেট করা:")
for i in np.nditer(arr):
  print(i, end=" ")
```

**আউটপুট:**

```
np.nditer() দিয়ে ইটারেট করা:
1 2 3 4 5 6 7 8 9
```


In [194]:
arr = np.linspace(1,10,10, dtype=int)
mod_arr = arr[1:5] # It not make copy it hold a portion of arr aray
print(mod_arr)
mod_arr[0] = 200
# it chnge the original array
print(arr)

[2 3 4 5]
[  1 200   3   4   5   6   7   8   9  10]


In [200]:
# we also make copy instead of taking portion of original array which not effecting in original array

arr = np.linspace(1,10,10, dtype=int)
mod_arr = arr[0:4].copy()
print(mod_arr)

mod_arr[1] = 200
print(mod_arr)
print(arr)

[1 2 3 4]
[  1 200   3   4]
[ 1  2  3  4  5  6  7  8  9 10]


### **Advance Indexing**

In [205]:
# we can access specific multiple index which not possible with slicing
arr = np.linspace(1,10,10, dtype=int)
print(arr)
values = arr[[0,1,3,4,5]]
print(values)

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 4 5 6]


In [216]:
# 2d array
arr = np.linspace(1,9,9, dtype=int)
arr = np.reshape(arr,(3,3))
print(arr)


#arr[[row_no_first_item, row_no_second_item,...row_no_n_item],[col_no_first_item, col_no_second_item,...col_no_n_item ]]
print(arr[[1,1],[1,2]])



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[5 6]


In [217]:
# filtering or reassing value with bollean expression

print(arr[arr>2])

# reassing value 0 to value greater than 8
arr[arr>8] = 0

print(arr)

[3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 0]]


### **Iteration**

In [221]:
arr = np.linspace(1,9,9, dtype=int)
arr = np.reshape(arr,(3,3))
# we can itereate with for
for row in arr:
  print(row)

# access each item
for row in arr:
  for col in row:
    print(col)

[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
4
5
6
7
8
9


In [225]:
# best way is doint it np.nditer()

arr = np.linspace(1,9,9, dtype=int)
arr = np.reshape(arr,(3,3))

for i in np.nditer(arr):
  print(i)

# it also print 3 darray with one loop
# our arr3 is 3d array

for i in np.nditer(arr3):
  print(i)


1
2
3
4
5
6
7
8
9
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0
